### DISCUSSION TITLE
OpenJDK 11 with cgroups v2 in OKD 4.9

### DISCUSSION THREAD

**Discussion by disposab1e** [okd-project/okd#1002] [Q&A] [answered]
The switch to cgroup v2 is a huge problem for all using older JDK's cause they depend on the cgroups v1 subsystem.

Is there a chance to install OKD 4.9 with cgroups v1?

**Comment by vrutkovs** [comment]
>Is there a chance to install OKD 4.9 with cgroups v1?

Yes, add `systemd.unified_cgroup_hierarchy=0` kernel argument via MC

**Comment by disposab1e** [comment, marked as answer]
@vrutkovs Thx for quick reponse! (as always!). 

Can this be done via `Adding day-1 kernel arguments` like....

```
cat << EOF > 99-openshift-machineconfig-master-kargs.yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-openshift-machineconfig-master-kargs
spec:
  kernelArguments:
    - systemd.unified_cgroup_hierarchy=0
EOF
```

**Reply by vrutkovs** [reply]
yes

**Comment by disposab1e** [comment]
It works! Brilliant!

**Comment by travier** [comment]
For reference: https://bugs.openjdk.java.net/browse/JDK-8230305
Any details about what exactly is broken and how would help here to make sure we don't break all Java based containers when moving to v2 by default.

**Comment by disposab1e** [comment]
I experienced a huge increase of memory usage. This starts with memory consumption increase in openshift-logging > 1.2Gi.  JBoss EAP > 500Mi and in our maven builds > 2Gi.

I work with OCP 4.9 and OKD 4.9 and run all apps and services in both clusters the same way. After switching to OKD 4.9 a lot of Java services, happy in OCP 4.9, fail in OKD 4.9.

Yes I saw this referenced Ticket and realized this is fixed in 15 and this is no option for us. I'm sure many people who run < JDK 15 will have problems vith JVMs in OKD 4.9.

You stated in  [Road to OKD 4.9](https://github.com/openshift/okd/discussions/948) that you have to add a note that cgroupsv2 is enabled on new installs. To be honest I think this really should be a warning!

**Reply by vrutkovs** [reply]
>To be honest I think this really should be a warning!

How would the warning look like? "Cluster is installed, but please be aware that some Java apps may start consuming more memory?"

**Comment by disposab1e** [comment]
The change to cgroup v2 may effect your running containers. Please check your containers (e.g. Java JDK before version 15) before you upgrade to OKD 4.9. If you're not sure please consider using cgroup v1 by adding a day-1 kernel argument with:

```
cat << EOF > 99-openshift-machineconfig-worker-kargs.yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-openshift-machineconfig-worker-kargs
spec:
  kernelArguments:
    - systemd.unified_cgroup_hierarchy=0
EOF
```
