### DISCUSSION TITLE
Bootstrap doesn't add any of the nodes

### DISCUSSION THREAD

**Discussion by davidtluong** [okd-project/okd#1009] [Q&A]
**Describe the bug**

Bootstrap times out with no errors and no nodes are added to the cluster.

Master nodes _seem_ to take the ignition file hosted by the bootstrap, since they all restart and boot to CoreOS after hitting the api-int successfully, but I'm not sure if it's actually taking the config considering I can ssh into my bootstraps but get an ssh key denied with the masters.

**Version** 

4.9

**How reproducible**

Every time

**Log bundle**

oc get csr --kubeconfig ../install/auth/kubeconfig
No resources found
oc get nodes --kubeconfig ../install/auth/kubeconfig
No resources found

install-config.yaml:
```
---
apiVersion: v1
baseDomain: psyiyi.com 
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: exeggcute
networking:
  clusterNetwork:
  - cidr: 10.100.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16 
platform:
  none: {}
pullSecret: '{mypullsecrethere}}}'
sshKey: |
  ssh-rsa ...
  ssh-rsa ...
```
[bootkubelogs.txt](https://github.com/openshift/okd/files/7673240/logs.txt)
