### DISCUSSION TITLE
Upgrade from 4.6 to 4.7.0-0.okd-2021-08-22-163618 stuck

### DISCUSSION THREAD

**Discussion by apmlima** [okd-project/okd#1052] [General]
**Describe the bug**
When upgrading the cluster from 4.6.0-0.okd-2021-02-14-205305   it says   Unable to apply 4.7.0-0.okd-2021-08-22-163618: some cluster operators have not yet rolled out
Upgrade stuck for 21h.

**Version**
AWS:  4.6.0-0.okd-2021-02-14-205305   ->  4.7.0-0.okd-2021-08-22-163618

**How reproducible**
oc adm upgrade --to=4.7.0-0.okd-2021-08-22-163618 --force=true --allow-upgrade-with-warnings

**Log bundle**
https://drive.google.com/file/d/1PY20S1HA85BSCX636dTKEGz4ib-pAhfi/view?usp=sharing

**Comment by vrutkovs** [comment]
>Some cluster operators are still updating: monitoring, service-ca
>Progressing: service-ca does not have available replicas

```
      state:
        waiting:
          message: container has runAsNonRoot and image will run as root
          reason: CreateContainerConfigError
```
See #810
