### DISCUSSION TITLE
Upgrade oVirt IPI install from 4.8 -> 4.9, oVirt CSI driver still at 4.8 and failing

### DISCUSSION THREAD

**Discussion by 0penshifty** [okd-project/okd#1053] [Q&A] [answered]
Hi there,

I recently upgraded an OKD IPI install on oVirt from 4.8 -> 4.9.0-0.okd-2021-12-12-025847.  It would appear as though the oVirt CSI Operator stayed at 4.8 (??), and I'm getting the ovirt-csi-driver-node pods crashing due to liveness probe failures.  Anybody else experience this?

Must-gather bundle:
https://nextcloud.endofday.com/s/3KgjAnJdd7pdy4K

**Comment by vrutkovs** [comment]
Using must-gather from https://github.com/openshift/okd/issues/1056:
>OVirtCSIDriverOperatorCRProgressing: OvirtDriverNodeServiceControllerProgressing:
      Waiting for DaemonSet to deploy node pods
`ovirt-csi-driver-node` DS in `openshift-cluster-csi-drivers` namespace stats are:
```
  status:
    currentNumberScheduled: 7
    desiredNumberScheduled: 7
    numberAvailable: 4
    numberMisscheduled: 0
    numberReady: 4
    numberUnavailable: 3
```

`ovirt-csi-driver-node-55pg5` pod on `okd-h8g8f-master-0` previously crashed:
```
2022-01-07T02:13:54.301476910Z I0107 02:13:54.166408       1 ovirt-csi-driver.go:45] Driver vendor csi.ovirt.org 0.1.1
2022-01-07T02:14:12.560832066Z F0107 02:14:12.556981       1 ovirt-csi-driver.go:66] Get "https://x-ipv4-0000000127-x:443/api?timeout=32s": dial tcp x-ipv4-0000000127-x:443: connect: no route to host
```
Apparently it can't reach oVirt API?
