### DISCUSSION TITLE
After upgrading to 4.9.0-0.okd-2022-01-29-035536 alertmanager pods fail to start

### DISCUSSION THREAD

**Discussion by coppin-j** [okd-project/okd#1089] [Q&A] [answered]
After upgrading to 4.9.0-0.okd-2022-01-29-035536 alertmanager pods fail to start, upgrade is currently hanging waiting for openshift monitoring to become available

level=info ts=2022-02-01T02:27:52.752Z caller=main.go:221 msg="Starting Alertmanager" version="(version=0.22.2, branch=master, revision=579e3c6879bad1ac3a1c4f7146b21f907980dafd)"
level=info ts=2022-02-01T02:27:52.752Z caller=main.go:222 build_context="(go=go1.16.6, user=root@01eb13d41cd1, date=20210819-19:19:21)"
level=warn ts=2022-02-01T02:27:52.818Z caller=cluster.go:251 component=cluster msg="failed to join cluster" err="3 errors occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 172.30.0.10:53: no such host\n\t* Failed to resolve alertmanager-main-1.alertmanager-operated:9094: lookup alertmanager-main-1.alertmanager-operated on 172.30.0.10:53: no such host\n\t* Failed to resolve alertmanager-main-2.alertmanager-operated:9094: lookup alertmanager-main-2.alertmanager-operated on 172.30.0.10:53: no such host\n\n"
level=info ts=2022-02-01T02:27:52.819Z caller=cluster.go:253 component=cluster msg="will retry joining cluster every 10s"
level=warn ts=2022-02-01T02:27:52.819Z caller=main.go:312 msg="unable to join gossip mesh" err="3 errors occurred:\n\t* Failed to resolve alertmanager-main-0.alertmanager-operated:9094: lookup alertmanager-main-0.alertmanager-operated on 172.30.0.10:53: no such host\n\t* Failed to resolve alertmanager-main-1.alertmanager-operated:9094: lookup alertmanager-main-1.alertmanager-operated on 172.30.0.10:53: no such host\n\t* Failed to resolve alertmanager-main-2.alertmanager-operated:9094: lookup alertmanager-main-2.alertmanager-operated on 172.30.0.10:53: no such host\n\n"
level=info ts=2022-02-01T02:27:52.819Z caller=cluster.go:671 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2022-02-01T02:27:52.872Z caller=coordinator.go:113 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=error ts=2022-02-01T02:27:52.873Z caller=coordinator.go:118 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="address nope: missing port in address"
level=info ts=2022-02-01T02:27:52.874Z caller=cluster.go:680 component=cluster msg="gossip not settled but continuing anyway" polls=0 elapsed=54.984853ms
**Version**

**How reproducible**

**Log bundle**
[must-gather.local.4874031688287403545.tar.gz](https://github.com/openshift/okd/files/7975723/must-gather.local.4874031688287403545.tar.gz)

**Comment by vrutkovs** [comment, marked as answer]
Your upgrade history is very strange:
```
    history:
    - ...
      state: Partial
      version: 4.9.0-0.okd-2022-01-29-035536
    - ...
      state: Partial
      version: 4.9.0-0.okd-2022-01-14-230113
    - ...
      state: Partial
      version: 4.8.0-0.okd-2021-10-24-061736
    - ...
      state: Partial
      version: 4.9.0-0.okd-2022-01-14-230113
    - ...
      state: Completed
      version: 4.8.0-0.okd-2021-10-24-061736
```
So after 4.9 -> 4.8 -> 4.9 partial upgrade your monitoring operator is still at 4.8.0-0.okd-2021-10-24-061736 version.

Try removing all CMO pods and see if it applies the latest 4.9 version?
