### DISCUSSION TITLE
Confused on which pullSecret to use

### DISCUSSION THREAD

**Discussion by aholen** [okd-project/okd#1196] [Q&A]
Hi, I'm trying to install a singlenode OKD 4.10 on a vsphere:
* Both `{"auths":{"fake":{"auth": "bar"}}}` and` {"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}} ` results in that the bootstrap can't download from quay, and the installation fails:  `Error: Error initializing source docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:81a4cb120f297de74a2d11fb914ffc4f33f792d44a462308eac61dc7d79e935e: Error reading manifest sha256:81a4cb120f297de74a2d11fb914ffc4f33f792d44a462308eac61dc7d79e935e in quay.io/openshift-release-dev/ocp-v4.0-art-dev: unauthorized: access to the requested resource is not authorized`
* I can successfully get a singlenode-cluster up by using the pullSecret from https://console.redhat.com/openshift/install/pull-secret  - but that's a OpenShift 60-days trial, not OKD.

**Comment by vrutkovs** [comment]
>singlenode OKD 4.10 on a vsphere

Are you using [assisted-installer](https://github.com/openshift/assisted-service/tree/master/deploy/podman#okd-configuration) or just `openshift-installer` to do that?

**Comment by aholen** [comment]
Hi, I'm using `openshift-installer` together with the  install-config.yml below: `./openshift-install create cluster --dir install_dir --log-level debug` 

I changed the installer-tag from 4.10.0-0.okd-2022-03-07-131213 to 4.10.0-0.okd-2022-04-23-131357 - and it looks like that helped..


```
apiVersion: v1
baseDomain: <redacted>
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: okdlab
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIP: 10.96.70.10
    cluster: <redacted>
    datacenter: <redacted>
    defaultDatastore: <redacted>
    ingressVIP: 10.96.70.20
    network: <redacted>
    password: <redacted>
    username: <redacted>
    vCenter: <redacted>
publish: External
pullSecret: '{"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}}'
sshKey: |
  <redacted>
```
