### DISCUSSION TITLE
OKD Changes Bearer Token

### DISCUSSION THREAD

**Discussion by pomland-94** [okd-project/okd#1355] [General]
Hey,
I use Grafana with the old build in Prometheus as Datasource. In okd I add the following to the Grafana-serviceaccount so that I can access Prometheus.
`oc adm policy add-cluster-role-to-user cluster-monitoring-view -z grafana-serviceaccount` after that I create a token to use it for Authentication against the Prometheus.

`oc create token grafana-serviceaccount` inside the Grafana Namespace. Everything works fine, I can authenticate against the Prometheus and can see Stats in Grafana. But every random minutes/hours the token changes and I hav etc change the Datasource, what is going wrong? I create the token without any expiration date. For Grafana I use the Operator.

**Comment by Reamer** [comment]
I think you should create a Secret which is bound to the Grafana ServiceAccount by the annotation `kubernetes.io/service-account.name`  Checkout https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token

**Comment by Reamer** [comment]
This is the content of my datasource config file. Mounted in the Grafana pod, of course. Under the path `/etc/grafana/provisioning/datasources`.
```
---
apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091"
    version: 1
    editable: false
    isDefault: true
    jsonData:
      timeInterval: "5s"
      httpHeaderName1: 'Authorization'
      tlsAuthWithCACert: true
    secureJsonData:
      httpHeaderValue1: "Bearer $__file{/var/run/secrets/kubernetes.io/serviceaccount/token}"
      tlsCACert: $__file{/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt}

```
