### DISCUSSION TITLE
certificate renewal for an ingress with HTTPS redirect

### DISCUSSION THREAD

**Discussion by cragia** [okd-project/okd#1375] [General]
Hello everyone!
I have a problem with the renewal of the certifications. Here I describe all the configuration and the problem.
### Configuration
I have the following configuration
#### Operator
I have installed the **cert-manager** operator, to be able to generate certificates automatically using **letsencrypt**.

#### Ingress
I have an ingress on the address (for example) foo.bar.com, configured like this:

    kind: Ingress
    apiVersion: networking.k8s.io/v1
    metadata:
      name: default
      namespace: example
    spec:
      tls:
        - hosts:
            - foo.bar.com
          secretName: foo-bar-tls
      rules:
        - host: foo.bar.com
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: foo-service
                    port:
                      name: http

#### Certificate
Then I defined the certificate this way:

    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: foo-certificate
      namespace: example
    spec:
      dnsNames:
        - foo.bar.com
      issuerRef:
        kind: ClusterIssuer
        name: letsencrypt
      secretName: foo-bar-tls

And with this configuration the certificate gets created without any problem.

#### Route
That ingress creates a route (once the certificate has been generated for the first time) that is configured like this:

    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: default-j8d4p
      namespace: example
      ownerReferences:
        - apiVersion: networking.k8s.io/v1
          kind: Ingress
          name: default
          controller: true
    spec:
      host: foo.bar.com
      path: /
      to:
        kind: Service
        name: foo-service
        weight: 100
      port:
        targetPort: http
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
        certificate: [...]
        key: [...]
      wildcardPolicy: None

### When the certificate is near the expiration

When the certificate expiration date is near, the operator tries to renew the certificate, and for this reason it correctly creates an ingress with this specification:

    kind: Ingress
    apiVersion: networking.k8s.io/v1
    metadata:
      generateName: cm-acme-http-solver-
      annotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: '0.0.0.0/0,::/0'
      namespace: example
      ownerReferences:
        - apiVersion: acme.cert-manager.io/v1
          kind: Challenge
          name: protel-firstupload-hvlxg-867449306-615812477
          uid: d1e55f97-8999-4f1a-9725-12a10e136612
          controller: true
          blockOwnerDeletion: true
      labels:
        acme.cert-manager.io/http-domain: '2859273096'
        acme.cert-manager.io/http-token: '638782808'
        acme.cert-manager.io/http01-solver: 'true'
    spec:
      rules:
        - host: foo.bar.com
          http:
            paths:
              - path: >-
                  /.well-known/acme-challenge/xxx
                pathType: ImplementationSpecific
                backend:
                  service:
                    name: cm-acme-http-solver-lmvlg
                    port:
                      number: 8089

And this creates automatically a Route configured like this:

    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      annotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: '0.0.0.0/0,::/0'
      name: cm-acme-http-solver-wp8jx-hblr2
      namespace: example
      ownerReferences:
        - apiVersion: networking.k8s.io/v1
          kind: Ingress
          name: cm-acme-http-solver-wp8jx
          uid: 00d55268-7a50-4c12-9a4d-9adc73323bf8
          controller: true
      labels:
        acme.cert-manager.io/http-domain: '2859273096'
        acme.cert-manager.io/http-token: '638782808'
        acme.cert-manager.io/http01-solver: 'true'
    spec:
      host: foo.bar.com
      path: /.well-known/acme-challenge/xxx
      to:
        kind: Service
        name: cm-acme-http-solver-lmvlg
        weight: 100
      port:
        targetPort: http
      wildcardPolicy: None

BUT this route will NEVER gets called, and I can verify it by clicking on the link shown, because in fact for that path it seems it's the ``foo-service`` that responds, and this means that the operator will never get the request...

### What I think it is happening
I noticed that the route is configured as ``insecureEdgeTerminationPolicy: Redirect`` and that is correct, because normally I want to have all the connections to be secure, but allowing the users to insert the address with HTTP, and redirecting them automatically.
BUT this means that when I call ``http://foo.bar.com/.well-known/acme-challenge/xxx`` it gets redirected to ``https://foo.bar.com/.well-known/acme-challenge/xxx`` and this means that only the route of my service gets matched, and for this reason the request gets sent to my service.

In fact, if I manually change the ``insecureEdgeTerminationPolicy`` to ``Allow``, the request gets not redirected to HTTPS, and so the right route get selected, so the request is directed to the right service... but as you can imagine, I don't want to enable the HTTP for that route, I only want secure requests coming in...

What should I do to avoid this problem?

thank you for your patience! :)

**Comment by nate-duke** [comment]
@cragia have you given the [openshift-routes](https://github.com/cert-manager/openshift-routes) addon for cert-manager a try? We're using it with little trouble in our OKD clusters.

**Reply by cragia** [reply]
hi @nate-duke! no, I never tried it, and I will for sure give it a try... although on their documentation it doens't seem to address this problem...
Anyway I will let you know if this solves it.

**Comment by nate-duke** [comment]
@cragia I mention it because it was specifically created to allow inter-operation between openshift routes and certificate-manager. It's not for this problem *specifically* but we're using it successfully in a couple of certificate-manager managed clusters here.

**Reply by cragia** [reply]
ok I got it. I think when I first needed to install the cert-manager and use it, that repo didn't exist, otherwise I would first tried this instead of the whole "ingress" thing...
Anyway, as soon as my test environment is equals to the production I will try it and let you know.

**Comment by cragia** [comment]
Hello again.
**Finally**! the test environment is finally ready, so I did some quick tests... but it seems I have the same problem.
The base route has the "Redirect" policy and so the request at the _/.well-known_ path gets basically redirected on https, and then basically it's my service that is replying...

@nate-duke can you show me the configuration of one of your routes, so that I can figure out what's different?

thank you!

**Reply by nate-duke** [reply]
> Hello again. **Finally**! the test environment is finally ready, so I did some quick tests... but it seems I have the same problem. The base route has the "Redirect" policy and so the request at the _/.well-known_ path gets basically redirected on https, and then basically it's my service that is replying...
> 
> @nate-duke can you show me the configuration of one of your routes, so that I can figure out what's different?
> 
> thank you!

Hey, no problem @cragia,

```yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nbc9-test
  namespace: nbc9-stuff
  annotations:
    cert-manager.io/issuer-kind: Issuer
    cert-manager.io/issuer-name: locksmith-issuer
spec:
  host: nbc9-test-05.linux.duke.edu
  to:
    kind: Service
    name: whoami-fitz-prod
    weight: 100
  port:
    targetPort: 80-tcp
  tls:
    termination: edge
    certificate: |
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      -----END RSA PRIVATE KEY-----
    insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None
  ```
 
 The magic bits are the cert-manager annotations that refer to our local ACME issuer which cert-manager and the magical openshift-routes addon will use to do all the verification, etc and stick the resulting cert/key into the route.

**Reply by cragia** [reply]
yes, well, basically it's the same as mine... can I see how you declared the issuer? I use a ClusterIssuer, but I guess it should work the same...

**Reply by nate-duke** [reply]
No Problem. Here's the issuer:
```yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: locksmith-issuer
spec:
  acme:
    email: my.email.address@you.can.guess.it.edu
    preferredChain: ""
    privateKeySecretRef:
      name: nate-locksmith
    server: https://locksmith.oit.duke.edu/acme/v2/directory
    solvers:
    - http01:
        ingress: {}
```

If you want you can refer to [our user facing documentation](https://okd-docs.cloud.duke.edu/examples/cert-manager/). There's route and issuer examples that our users use there.
