### DISCUSSION TITLE
Investigate online resources for setting up an OKD cluster

### DISCUSSION THREAD

**Discussion by binnes** [okd-project/okd#1409] [Ideas]
As part of a community workgroup initiative to provide better getter started information to help people get started installing OKD we want to investigate what tutorials are available

**Comment by sherine-k** [comment]
While quickly looking yesterday I found https://itnext.io/guide-installing-an-okd-4-5-cluster-508a2631cbee (2020)

**Reply by jeffmccune** [reply]
I followed https://itnext.io/guide-installing-an-okd-4-5-cluster-508a2631cbee over the weekend too and got a working cluster.

I spent the most time on getting my worker and controller hostnames into an externally resolvable zone because of the [user-provisioned DNS requirements](https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-dns-user-infra_installing-bare-metal).  I later learned this wasn't necessary and tore the whole private network down.  I wish the DNS requirements were more clear because this was the biggest time sink for me.  It wasn't clear if my existing internal DNS met the installation requirements or not, so I followed the guide to the letter since other community members reported it worked.

I learned my existing "example.lan" internal zone works fine for controller and worker host names as long as I expose api.okd4.example.com, api-int.okd4.example.com, and *.apps.okd4.example.com in an external zone.

Also, the PTR records for the load balancer are incorrect and unnecessary, which was the only clue I had the "requirements" weren't really required.  Each PTR record should only have one value, not multiple as shown in the documentation.

**Reply by binnes** [reply]
HI Jeff, did you install a 4.5 cluster or use the latest 4.11 installer bundle to install an up to date cluster?

**Reply by jeffmccune** [reply]
I used the latest 4.11 bundle `4.11.0-0.okd-2022-11-19-050030` on proxmox (kvm) with no customizations:

```yaml
apiVersion: v1
metadata:
  name: ocp4
baseDomain: example.com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: 'REDACTED but valid for cloud.openshift.com'
capabilities:
  baselineCapabilitySet: None
  additionalEnabledCapabilities:
  - openshift-samples
```
