### DISCUSSION TITLE
Upgrade to 4.12 stuck at 94%

### DISCUSSION THREAD

**Discussion by dkoci** [okd-project/okd#1480] [Q&A]
Hi.
I have some issue. I would like to upgrade okd from latest 4.11 to 4.12 version. Upgrade stuck at 94% with error

![image](https://user-images.githubusercontent.com/5565897/214384552-90a950a7-740e-4b5e-a965-0d294b68395d.png)

Cluster operator kube-apiserver should not be upgraded between minor versions: 
`KubeletMinorVersionUpgradeable: Kubelet minor versions on 7 nodes will not be supported in the next OpenShift minor version upgrade.`

console operator is also degraded:
`ConsoleNotificationSyncDegraded: rpc error: code = Unavailable desc = keepalive ping failed to receive ACK within timeout`

must-gather logs:
[must-gather.tar.gz](https://github.com/okd-project/okd/files/10499320/must-gather.tar.gz)

**Comment by melledouwsma** [comment]
```
$ tree -L 1 must-gather.local.5071121045627036510/
must-gather.local.5071121045627036510/
├── event-filter.html
├── registry-redhat-io-openshift-logging-cluster-logging-rhel8-operator-sha256-2b219ac43c49e111bd28bf270ad0086cfe84b94889faf8d40d6c3d6d26ea314f
└── timestamp

2 directories, 2 files
```

This is a cluster-logging must-gather that only contains information on the logging stack. Please provide a full `oc adm must-gather`.

**Reply by dkoci** [reply]
@melledouwsma complete gather logs: https://wetransfer.com/downloads/e39b0eca6f87a14a8f6151ed49fefbba20230126111513/6bd497

**Comment by melledouwsma** [comment]
Thanks! Are you sure you're upgrading to 4.12? The ClusterVersion from the must-gather says you're performing a 4.10 to 4.11 upgrade. From `oc get clusterversion -o yaml`:

```yaml
status:
  desired:
    image: registry.ci.openshift.org/origin/release@sha256:27c99f5b7734f773a7981b9e527417edcda0eee217117632198d64aa33e95c46
    version: 4.11.0-0.okd-2023-01-14-152430
```

The upgrade has already updated all the worker nodes, but is stuck on the masters. From `oc get mcp master -o yaml`:

```yaml
status:
  conditions:
  - lastTransitionTime: '2023-01-21T21:42:58Z'
    message: 'Node okd-01-zvldl-master-1 is reporting: "unexpected on-disk state validating
      against rendered-master-4faba702afb193239685ebe1c5c7a053: Missing expected kernel
      arguments: [mitigations=off intel_pstate=disable]", Node okd-01-zvldl-master-0
      is reporting: "unexpected on-disk state validating against rendered-master-4faba702afb193239685ebe1c5c7a053:
      Missing expected kernel arguments: [mitigations=off intel_pstate=disable]",
      Node okd-01-zvldl-master-2 is reporting: "unexpected on-disk state validating
      against rendered-master-4faba702afb193239685ebe1c5c7a053: Missing expected kernel
      arguments: [mitigations=off intel_pstate=disable]"'
    reason: 3 nodes are reporting degraded status on sync
    status: 'True'
    type: NodeDegraded
```

The update will not continue as long as the unexpected on-disk state exists. This is a duplicate of #1474.
