### DISCUSSION TITLE
OKD/OpenShift install on Baremetal: Proxmox/QEMU

### DISCUSSION THREAD

**Discussion by GannonTdW** [okd-project/okd#1487] [General]
Hello,

This is more a question than a bug report, but I didn't really find where to put this question

I would like to install OKD (or OpenShift) on my home Lab proxmox.
I have configured all DNS records on my OPNsense  and I have the oc client and the openshift-install.

But I don't understand how to create VMs.

With the `openshift-instal create manifest|cluster` command, I have the choice between azure, gcp, openstack, vsphere ... but not proxmox / qemu.

In some old blog post or the lastest [okd doc (installation-initializing-manual_installing-bare-metal)](https://docs.okd.io/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-initializing-manual_installing-bare-metal), I see mention of a `install-config.yaml` file but I don't have it in [ openshift-install-linux-4.12.0-0.okd-2023-01-21-055900.tar.gz ]( openshift-install-linux-4.12.0-0.okd-2023-01-21-055900.tar.gz )

I simply create it based on https://github.com/okd-project/okd/issues/27 ?

Thank you for your help.

PS: To be closer to what I have at work, I would like to use Fedora CoreOS

**Comment by tothlali** [comment]
My install-config.yaml (3 masters, 2 workers) (service.okd.local is the machine where oc runs) :

```
apiVersion: v1
baseDomain: local
compute:
- hyperthreading: Enabled   
  name: worker
  replicas: 2 
controlPlane:
  hyperthreading: Enabled   
  name: master 
  replicas: 3 
metadata:
  name: okd 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16
platform:
  none: {} 
pullSecret: '{"auths": {"fake": { "auth" : "bar"}}}' 
sshKey: 'ssh-ed25519 ... root@service.okd.local' 
```
