### DISCUSSION TITLE
[OKD 4.12] [coredns] Why did we remove the fix for coredns CPU issues

### DISCUSSION THREAD

**Discussion by fortinj66** [okd-project/okd#1515] [General]
coredns still tries to use Network Managers resolv.conf file:

```
  initContainers:
    - name: render-config-coredns
      image: >-
        quay.io/openshift/okd-content@sha256:d6c6e185d2a28218270fc7a998525b2ca175e1e1babf13385980d7fb5683b15c
      command:
        - runtimecfg
        - render
        - /var/lib/kubelet/kubeconfig
        - '--api-vips'
        - 10.102.5.6
        - '--ingress-vips'
        - 10.102.5.7
        - /config
        - '--out-dir'
        - /etc/coredns
        - '--resolvconf-path'
        - /var/run/NetworkManager/resolv.conf`
```
        
which still points to 127.0.0.53...  Which always fails:

```
# pwd
/var/run/NetworkManager

# cat resolv.conf
# Generated by NetworkManager
search maeagle.corp
nameserver 127.0.0.53
options edns0 trust-ad
```

There was a fix that ran a service to fix this in 4.9 and 4.10

```
[Unit]
Description=Fix NM resolv.conf issues with coreDNS
DefaultDependencies=no
Requires=systemd-resolved.service
After=systemd-resolved.service fix-resolv-conf-dot.service network-online.target
Before=crio.service

[Service]
Type=oneshot
ExecStart=/usr/bin/cp /run/systemd/resolve/resolv.conf /var/run/NetworkManager/resolv.conf

[Install]
WantedBy=multi-user.target
```

It is very frustrating when fixed/worked-around  issues reappear.
