### DISCUSSION TITLE
unable to authenticate okd against keycloak 21.1.1

### DISCUSSION THREAD

**Discussion by jas01** [okd-project/okd#1594] [General]
I'm using OKD with keycloak authentication. It's was working until I upgrade keycloak to 21.1.1
Of course my first reflexe was «the problem are with keycloak», but I got many other application who authenticate perfectly with keycloak 21.1.1 (at least gitlab, discours, tulipchat, etc.)

**Version**

4.12.0-0.okd-2023-04-16-041331

**How reproducible**
The okd can authenticate with Keycloak 20.0.2, but not working with 21.1.1 
It's 100% reproductible.

**Comment by jas01** [comment]
I eventually find out the problem, I write this comment in case someone got the same issue. 

It come from the name of the object 
```yaml
kind: OAuth
metadata:
  labels:
    app.kubernetes.io/instance: openshift-config
  name: cluster
spec:
  identityProviders:
  - mappingMethod: claim
    name: OIDC_something
```
if the name containt a space (like OIDC something) it's not working anymore with keycloak 21.1.1  but without it's working well.
