### DISCUSSION TITLE
/etc/resolv.conf search domains

### DISCUSSION THREAD

**Discussion by BonzTM** [okd-project/okd#1634] [Q&A] [answered]
What is the most appropriate way to permanently modify the `/etc/resolv.conf` on a node in an OKD 4.13 cluster since systemd-resolved is worked-around?

The search domain on each node is propagated to my pods and resulting in hundreds of thousands of invalid forwarded lookups.

I've currently applied a machineConfig that overwrites `/run/systemd/resolve/resolv.conf` with a custom file, but I want to make sure I follow appropriate procedures and don't circumvent any systems in-place

**Comment by vrutkovs** [comment, marked as answer]
Set nameserver / search domains in NetworkManager - it would update `/var/run/NetworkManager/resolv.conf` and subsequently `/run/systemd/resolve/resolv.conf`

**Reply by goern** [reply]
is that to be done via Kubernetes NMState Operator's NodeNetworkConfigurationPolicy ?

**Reply by LennertMertens** [reply]
How did you guys solve this? @goern  do you have a solution?

**Comment by BonzTM** [comment]
> is that to be done via Kubernetes NMState Operator's NodeNetworkConfigurationPolicy ?

I attempted to apply a `NodeNetworkConfigurationPolicy` config to the `nmstate.io/v1` api first, only to realize that those CRDs don't exist in OKD (even though OpenShift 4.13 documentation tells you to do it this way).

Ultimately I made the modifications via `nmcli` to the interface directly on each node.
Something like: `nmcli con mod ens18 ipv4.dns-search "foo.bar.com"`

Edit:  It looks like you can install it after the fact: https://docs.okd.io/latest/networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.html

**Comment by goern** [comment]
> Edit: It looks like you can install it after the fact: https://docs.okd.io/latest/networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.html

you can, that's what I did. But I think I did not fully understand the NNCP. Do you still have the .yaml you created around?

**Comment by BonzTM** [comment]
> > Edit: It looks like you can install it after the fact: https://docs.okd.io/latest/networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.html
> 
> you can, that's what I did. But I think I did not fully understand the NNCP. Do you still have the .yaml you created around?


Here is the OpenShift documentation:
https://docs.openshift.com/container-platform/4.13/networking/k8s_nmstate/k8s-nmstate-updating-node-network-config.html

And the very simple yaml I was going to apply before I ran `nmcli`

```yaml
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: 99-okd-worker-resolvconf
spec:
  nodeSelector: 
    node-role.kubernetes.io/worker: "" 
  desiredState:
    dns-resolver: 
      config:
        server:
        - 10.0.10.1
        - 10.0.10.2
        search:
        - domain.lan
   ```

**Comment by LennertMertens** [comment]
I'm running into some issues configuring the search domains. I tried applying the followin NNCP but when doing that, the cluster fails to update, service routes and API becomse unavailable and starts throwing 503 service errors.

NNCP:
```yml
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: okd-nodes-resolvconf

spec:
  maxUnavailable: 1
  desiredState:
    dns-resolver: 
      config:
        server:
          - 10.24.12.17
          - 10.242.5.17
        search:
          - cluster.local
          - k8s.cluster.be # basedomain
          - rmp.be
          - xyz.be
          - servers.xyz.be
          - servers.dmf.be
```

Anybody that was able to solve this issue? Thanks
