### DISCUSSION TITLE
Using iSCSI as PV: Restarting Pods after sometime fails: Unable to attach or mount volume

### DISCUSSION THREAD

**Discussion by horvaro** [okd-project/okd#1663] [Q&A] [answered]
Setup:
Server Version: 4.11.0-0.okd-2022-12-02-145640
Kubernetes Version: v1.24.0-2568+56584349e9412b-dirty
3 Master and 6 Worker Nodes with Fedora CoreOS 36 amd64 Kernel 6.0.10-200.fc36.x86_64, Kubelet Version v1.24.6+5658434

I encountered the following problem with different iSCSI server software (Synology NAS, CentOS and targetcli, Windows Server and its iSCSI Server):

I am running a Deployment of a Java Springboot Pod with the following PV and PVC definition:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-iscsi-srvstorage-disk1
  labels:
    name: archive
    app: important-app
    volume-env: dev
spec:
  capacity:
    storage: 24576Gi   # == 24TB
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 192.168.244.244:3260
    iqn: iqn.1991-05.com.microsoft:srvstorage-iscsitarget-01-target
    lun: 0
    initiatorName: iqn.2023-07.org.domain:srvstorage-initiator-target-01
    fsType: "ext4"
    chapAuthDiscovery: false
    chapAuthSession: true
    timeoutSeconds: 60
    secretRef:
      name: srvstorage-iscsitarget01-secret
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - okd4-worker4.domain.org
  claimRef:
    name: pvc-iscsi-srvstorage-disk1
    namespace: important-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-iscsi-srvstorage-disk1
  namespace: important-app
  labels:
    app: important-app
    name: archive
spec:
  accessModes:
  - ReadWriteOnce
  volumeName: pv-iscsi-srvstorage-disk1
  storageClassName: ""
  resources:
    requests:
      storage: 24576Gi
  selector:
    matchLabels:
      volume-env: dev
```
(I started using `nodeAffinity` in the PV definition for some stability. Without it some Pods won't be running on the same Worker, and mounting a LUN to two separate Hosts does not work)

The PVC is used in the Pod/Deployment like this:
```yaml
[...]
          volumeMounts:
            - name: storage-iscsi-disk1
              mountPath: /iscsi-disk1
[...]
      volumes:
        - name: storage-iscsi-disk1
          persistentVolumeClaim:
            claimName: pvc-iscsi-srvstorage-disk1
[...]
```

When I first deploy the app, and the iSCSI Disk is empty (Clean filesystem: `wipefs --all` and `mkfs.ext4 -m 1 -O dir_index,filetype`), the Pods get assigned to the worker nr. 4 and after a few moments it is running with the correct volumemount.  
I let my app running and fill the disk with some data.

Now: If i delete the pod or restart the rollout, the Pod won't start, because the volume cannot be mounted. 
Events for the Pod:
- Successfully assigned important-app/app-6cd5f666f5-69tr2 to okd4-worker4.domain.org by okd4-master1.domain.org
- AttachVolume.Attach succeeded for volume "pv-iscsi-srvstorage-disk1"
- Unable to attach or mount volumes: unmounted volumes=[storage-iscsi-disk1], unattached volumes=[storage-iscsi-disk1]: timed out waiting for the condition

Looking into the connected iSCSI sessions on the worker does not work, because the command `iscsiadm -m session` does not print any output (via oc debug node/...).
I am certain that the login to the target worked. The iSCSI server logs, that the iSCSI initiator could log in. Furthermore, I can see a new device on the host with the above-described size. I can even log out of the iSCSI target manually (again without any output on the console), after which that mentioned device is gone.

What I have tried until now:
- Deploy Pod to another Worker (Setting NodeAffinity of the PV to another Node)
- Restart the Node, on which the Pod runs, and the PV is mounted
- Restart iSCSI Server
- Check iSCSI configuration (allowed IQN, IP, open ports, backing devices on the server, CHAP secrets)
- Manually login to iSCSI target before deployment
- Delete and re-apply PV and PVC definition
- Only scale/run 1 single pod

Am I missing some crucial configuration?
Or is this iSCSI setup not how it is done?

Thanks for your help in advance.

**Comment by LorbusChris** [comment]
Are there any SELinux denials? `journalctl -t setroubleshoot` should give some insight

**Reply by horvaro** [reply]
I just run the command. No, there are no entries:
```
sh-5.2# journalctl -t setroubleshoot
-- No entries --
```

**Comment by horvaro** [comment]
Running the command `journalctl -u '*iscsi*' -f` shows that on creating the pod which uses the definied PVC/PV the connection can be made to the iscsi target server:

```
Jul 25 14:27:32 okd4-worker4.domain.org iscsid[1584]: iscsid: Connection3:0 to [target: iqn.1991-05.com.microsoft:srvstorage-iscsitarget-01-target, portal: 192.168.244.244,3260] through [iface: 192.168.244.244:3260:pv-iscsi-srvstorage-disk1] is operational now
```

**Comment by horvaro** [comment]
I will try the same setup with OKD 4.13 and FedoraCoreOS 38, hoping that this helps.

**Reply by horvaro** [reply]
With OKD 4.13 and Fedora CoreOS 38, mounting the used iscsi LUN is still not possible.
At least i get now output from the iscsiadm command:

`iscsiadm -m session`:
```
...
tcp: [3] 192.168.244.244:3260,1 iqn.1991-05.com.microsoft:srvstorage-iscsitarget-01-target (non-flash)
```


`iscsiadm -m session -P3`
```
...
Target: iqn.1991-05.com.microsoft:srvstorage-iscsitarget-01-target (non-flash)
...
                ************************
                Attached SCSI devices:
                ************************
                Host Number: 34 State: running
                scsi34 Channel 00 Id 0 Lun: 0
                        Attached scsi disk sdd          State: running
```

Yet, the Pod has trouble to mount the disk:
`Unable to attach or mount volumes: unmounted volumes=[storage-iscsi-disk1], unattached volumes=[storage-iscsi-disk1]: timed out waiting for the condition`

**Comment by horvaro** [comment]
Investigating this issue further lead me to the conclusion, that a used volume may need a lot of time to mount, because k8s check all files for their owner ship when mounting to a pod:
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods

For a 24TB drive, which currently "only" holds 100Mio files, this could take ages.
Setting `fsGroupChangePolicy: "OnRootMismatch"` in the `securityContext` of the Pod should help. (see link above)
But what if the Pod gets really another UID/GID in `fsGroup` and it needs to change all the file ownerships?

What is the correct way in OpenShift, to define a `securityContext` and/or a SCC which always uses the same UID/GID for a given Pod and the PV/PVC?

**Reply by horvaro** [reply]
Adding to this:
The SELinux labels will also be checked and set for a volume that gets mounted to a pod. This has the same issue which a large volume with already a big pile of files on it.
I found a description, for those who also have this issue, on redhat.com, how to disable the relable process:
https://access.redhat.com/solutions/6221251
(tldr: you'll need to somehow add the type 'spc_t' to the seLinuxOptions inside the securityContext for each pod)

**Comment by horvaro** [comment]
Using `fsGroupChangePolicy: "OnRootMismatch"` in the `securityContext` brought me some steps further.
Now the Pod cannot start because of  
`Error: context deadline exceeded`  
and  
`Error: kubelet may be retrying requests that are timing out in CRI-O due to system load. Currently at stage container volume configuration: context deadline exceeded: error reserving ctr name k8s__80da78e1-6ff7-4e91-bc70-8c35b5337af8_0 for id 62733eaf48a2ec78804ce2937a2bb179f3bc8a367d1161be3f7075fc316ea1f7: name is reserved`  
  

Is there maybe a timeout which I need to set higher, so that the mounting of the disk is not interrupted?

**Reply by horvaro** [reply]
Pod Events:  
```
  Type     Reason                  Age                 From                     Message
  ----     ------                  ----                ----                     -------
  Normal   SuccessfulAttachVolume  46m                 attachdetach-controller  AttachVolume.Attach succeeded for volume "XXX"
  Normal   AddedInterface          46m                 multus                   Add eth0 [10.128.4.116/23] from openshift-sdn
  Normal   Pulled                  46m                 kubelet                  Container image "radial/busyboxplus:curl" already present on machine
  Normal   Pulled                  46m                 kubelet                  Container image "busybox" already present on machine
  Normal   Started                 46m                 kubelet                  Started container dependency-check
  Normal   Created                 46m                 kubelet                  Created container dependency-check
  Normal   Created                 46m                 kubelet                  Created container init
  Normal   Started                 46m                 kubelet                  Started container init
  Warning  Failed                  27m                 kubelet                  Error: kubelet may be retrying requests that are timing out in CRI-O due to system load. Currently at stage container volume configuration: context deadline exceeded: error reserving ctr name k8s_XXXXXX_80da78e1-6ff7-4e91-bc70-8c35b5337af8_0 for id c2c26d30457865cf656c0dab5d02a5381250fcbc7093a06fcc3d9b7460da02c9: name is reserved
  Normal   Pulled                  23m (x12 over 45m)  kubelet                  Container image "XXXXX" already present on machine
  Warning  Failed                  15m                 kubelet                  Error: kubelet may be retrying requests that are timing out in CRI-O due to system load. Currently at stage container volume configuration: context deadline exceeded: error reserving ctr name k8s_XXXXXX_80da78e1-6ff7-4e91-bc70-8c35b5337af8_0 for id 62733eaf48a2ec78804ce2937a2bb179f3bc8a367d1161be3f7075fc316ea1f7: name is reserved
  Warning  Failed                  68s (x18 over 43m)  kubelet                  Error: context deadline exceeded
```

**Comment by horvaro** [comment, marked as answer]
Summarizing my monologue here:
- Mounting an already used (aka. with files populated) volume will trigger validation processes, like for the correct owner of the files and folders and the correct SELinux labels.
- Depending on the volumesize and the amount of files and folders it already houses, these validations could take a (too) long time.
- These checks can be disabled
  - `fsGroupChangePolicy: OnRootMismatch`: Only trigger the ownership checking process, if the root folder of the volume has not the same group UID as the pods `fsGroup` setting. (Also check that)
  - `type: spc_t`: seLinuxOption to define the pod with 'super privileges' so that it disables the SELinux relabeling. (But also here: Check which labels the Pods need, based on the files of the volume)
    - Quote: "spc_t is a special SELinux type, standing for super privileged container type. A container having this type will not be constrained by SELinux policies."
    - This setting can be set on different ways in Openshift. See links down below.

Such a `securityContext` for a pod could look like this:
```
  securityContext:
    seLinuxOptions:
      type: spc_t
      level: 's0:c27,c24'
    runAsUser: 1000710000
    runAsGroup: 1000710000
    fsGroup: 1000710000
    fsGroupChangePolicy: OnRootMismatch
```

Documentation in K8s for volume permission check:
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods

Documentation on how to add the SELinux relabel setting:
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods
