### DISCUSSION TITLE
Master Node not using cluster Proxy for 1 Url ignoring noProxy setting

### DISCUSSION THREAD

**Discussion by ffppmm** [okd-project/okd#1737] [General]
Hi,
We recently deployed a Proxy to our cluster and everything works fine, except one little thing. One of the master nodes tries to reach the following oauth Url using the Proxy. But we excluded the Url in the noProxy setting.
```
apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
  name: cluster
spec:
  httpProxy: 'http://XXX.XXX.XXX.XXX:3128'
  httpsProxy: 'http://XXX.XXX.XXX.XXX:3128'
  noProxy: >-
    .okd.example.com,.yy.okd.example.com,.apps.yy.okd.example.com
  readinessEndpoints:
    - 'http://www.example.com'
    - 'https://www.example.com'
  trustedCA:
    name: ''
status:
  httpProxy: 'http://XXX.XXX.XXX.XXX:3128'
  httpsProxy: 'http://XXX.XXX.XXX.XXX:3128'
  noProxy: >- .apps.yy.okd.example.com,.cluster.local,.yy.okd.example.com,.okd.example.com,.svc,10.0.0.0/16,10.128.0.0/14,127.0.0.1,172.30.0.0/16,api-int.xx.okd.example.com,localhost
```
For whatever reason we see in the proxy logs the following Connect:
```
[14/Sep/2023:11:15:00 +0200] master1.okd.example.com oauth-openshift.apps.yy.okd.example.com:443 "CONNECT oauth-openshift.apps.yy.okd.example.com:443 HTTP/1.1" 503 0 "-" "Go-http-client/1.1" TAG_NONE:HIER_NONE
```
Fyi we use squid. This shouldn't be happening in my opinion, because of the noProxy Setting

Version: 4.12.0-0.okd-2023-04-16-041331
We have this behavior on all our clusters with the same Version

Why is this happening? Any thoughts on this?
Regards Philipp
