### DISCUSSION TITLE
What configures the serviceNetwork?

### DISCUSSION THREAD

**Discussion by Nadyita** [okd-project/okd#1839] [Q&A]
I'm trying to setup OKD with 3 control planes and 3 workers on VPS servers of GoDaddy. There is 0 k8s infrastructure or help provided, not private networks between the servers, or even load balancers. It's even challenging to boot CoreOS at all, because you cannot boot from arbitrary iso files, but I managed to get 2 load balancers (haproxy), the bootstrap server and master0 up following [this guide](https://docs.okd.io/latest/installing/installing_platform_agnostic/installing-platform-agnostic.html). However, I have no idea where the serviceNetwork (172.30.0.0/16 as per default) is configured. I don't see this network being brought up on any of the hosts. I'm doing regular networking for all machines via kernel cmdline `rd.neednet=1 ip=<lotsofthings>`.

Am I supposed to set this up myself somehow (or have it provided by my hoster, haha!), or *should* okd create this network automatically? My machine-config-server on master0 currently gives a 500 when querying a master ignition file for master1, and the logs are spamming with network errors.

My `install-config.yaml`:
```yaml
apiVersion: v1
baseDomain: nadybot.org
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: okd
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '{"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}}'
sshKey: 'ssh-ed25519 …'
```
[log-bundle-20231226231811.tar.gz](https://github.com/okd-project/okd/files/13773933/log-bundle-20231226231811.tar.gz)
