### DISCUSSION TITLE
MountVolume.NewMounter initialization failed for volume "gitlab-gitaly-pv" : path "/root/a" does not exist

### DISCUSSION THREAD

**Discussion by ricky-chaoju** [okd-project/okd#1892] [General]
Hello, my operators on OKD and OpenShift try to install GitLab to create it with the following yaml. GitLab will automatically create 4 PVCs, repo-data-gitlab-gitaly-0, redis-data-gitlab-redis-master-0 , gitlab-minio and data-gitlab-postgresql-0, I used the following to create one of the PVs that was successfully bound to the PVC, and also at 2001-b030-801e-0300-0000-0000-0000-103e.hinet-ip6.hinet The corresponding folder is created on the .net node, but the Pod is always in the ContainerCreating state. The log shows that MountVolume.NewMounter initialization failed for volume "gitlab-minio-pv" : path "/mnt/gitlab/minio" does not exist and Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition, what should I do? Thank you.

create GitLab yaml:
<img width="899" alt="截圖 2024-02-22 上午11 10 24" src="https://github.com/okd-project/okd/assets/109416633/e51a3255-bde4-44b5-8cb7-560133d46259">

PV yaml:
<img width="899" alt="截圖 2024-02-22 上午11 10 29" src="https://github.com/okd-project/okd/assets/109416633/2404a2af-00ac-4669-87e2-14d59667dbf2">

<img width="1703" alt="截圖 2024-02-22 上午11 04 42" src="https://github.com/okd-project/okd/assets/109416633/e458cfe4-638e-48a1-81bc-b5fac11389c3">
<img width="899" alt="截圖 2024-02-22 上午11 05 34" src="https://github.com/okd-project/okd/assets/109416633/8dc9c465-77d6-4ef7-ae82-ab79886c6199">

**Comment by madpearl** [comment]
When you use HostPath you should use something like this:

https://docs.okd.io/4.14/storage/persistent_storage/persistent_storage_local/persistent-storage-hostpath.html

````
apiVersion: v1
kind: Pod
metadata:
  name: test-host-mount
spec:
  containers:
  - image: registry.access.redhat.com/ubi9/ubi
    name: test-container
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - mountPath: /host
      name: host-slash
  volumes:
   - name: host-slash
     hostPath:
       path: /
       type: ''
```
---
```
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: task-pv-volume 
    labels:
      type: local
  spec:
    storageClassName: manual 
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce 
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: "/mnt/data" 
```


`

**Reply by ricky-chaoju** [reply]
Thank you for your reply. Now I got a new error and CrashLoopBackOff appears on the pod. How can I adjust the settings? thank you

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-gitlab-postgresql-0
  labels:
    type: local
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: gitlab
    app.kubernetes.io/name: postgresql
spec:
  storageClassName: ""
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/gitlab/data-gitlab-postgresql-0"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "2001-b030-801e-0300-0000-0000-0000-103e.hinet-ip6.hinet.net"
  claimRef:  
    namespace: gitlab-system  
    name: data-gitlab-postgresql-0
```
<img width="2056" alt="截圖 2024-02-23 下午3 22 42" src="https://github.com/okd-project/okd/assets/109416633/10036471-2b9a-42cf-8323-0efb88e887c8">


my log:
```
Begin parsing .tpl templates from /etc/gitaly/templates
Writing /etc/gitaly/config.toml
Copying other config files found in /etc/gitaly/templates to /etc/gitaly
Starting Gitaly
{"component": "gitaly","subcomponent":"gitaly","latencies":[0.001,0.005,0.025,0.1,0.5,1,10,30,60,300,1500],"level":"info","msg":"grpc prometheus histograms enabled","pid":1,"time":"2024-02-23T07:20:46.691Z"}
{"component": "gitaly","subcomponent":"gitaly","level":"info","msg":"Starting Gitaly","pid":1,"time":"2024-02-23T07:20:46.691Z","version":"16.9.0"}
{"component": "gitaly","subcomponent":"gitaly","duration_ms":0,"level":"info","msg":"finished initializing cgroups","pid":1,"time":"2024-02-23T07:20:46.692Z"}
{"component": "gitaly","subcomponent":"gitaly","duration_ms":63,"level":"info","msg":"finished unpacking auxiliary binaries","pid":1,"time":"2024-02-23T07:20:46.755Z"}
{"component": "gitaly","subcomponent":"gitaly","duration_ms":0,"level":"info","msg":"finished initializing bootstrap","pid":1,"time":"2024-02-23T07:20:46.755Z"}
{"component": "gitaly","subcomponent":"gitaly","duration_ms":1,"level":"info","msg":"finished initializing command factory","pid":1,"time":"2024-02-23T07:20:46.757Z"}
{"component": "gitaly","subcomponent":"gitaly","duration_ms":36,"level":"info","msg":"finished detecting git version","pid":1,"time":"2024-02-23T07:20:46.793Z"}
{"component": "gitaly","subcomponent":"gitaly","level":"info","msg":"clearing disk cache object folder","pid":1,"storage":"default","time":"2024-02-23T07:20:46.794Z"}
```
