### DISCUSSION TITLE
Persistant Storage not working

### DISCUSSION THREAD

**Discussion by aheath1992** [okd-project/okd#1986] [Q&A]
I have a single node OKD install, im trying to setup NFS storage and I follow the documentation [here](https://docs.okd.io/latest/storage/persistent_storage/persistent-storage-nfs.html) and I can see that it is bound
```
NAME     CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                   STORAGECLASS   REASON   AGE
nfs-pv   50Gi       RWO            Retain           Bound    openshift-image-registry/nfs-pv-claim                           38s
```

but when I try to install the awx operator I get `no persistent volumes available for this claim and no storage class is set` on the postgress container, so Im not sure where the missing step is, and why its not able to use the NFS storage setup.

```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/nfs/okd
    server: 192.168.118.201
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-claim
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 50Gi 
  volumeName: nfs-pv
```
