### DISCUSSION TITLE
Software raid in OKD: error: Not POSIX compatible.

### DISCUSSION THREAD

**Discussion by edubach** [okd-project/okd#2021] [General]
Hello everyone,

When trying to configure a BMH to use software raid:

`spec:`
`  raid:`
`    softwareRAIDVolumes:`
`    - level: "1"`
`      sizeGibibytes: 50`
`    - level: "0"`

in a OKD "4.15.0-0.okd-2024-03-10-010116" I am getting the error:

`
Clean step raid.create_configuration failed on node ef09da1d-2b73-4826-8184-a4926da02fc5. Failed to create md device /dev/md0 on /dev/sda1 /dev/sdb1: Unexpected error while running command. Command: mdadm --create /dev/md0 --force --run --metadata=1 --level 1 --name /dev/md0 --raid-devices 2 /dev/sda1 /dev/sdb1 Exit code: 2 Stdout: '' Stderr: 'mdadm: Value "/dev/md0" cannot be set as name. Reason: Not POSIX compatible.\n'
`

This error is due to a new version of mdadm being used, and manual inspection shows that if "--name /dev/md0" is changed to "--name raid0", or omitted altogether, the command will work. Now, for software raid, "name" is not accepted, so I can't pass it to the command via bmh yaml, and the name is autogenerated. 
Is there a way I can change the scripts used for the configuration? Where would they be?

Thanks a lot for any help.

**Comment by JaimeMagiera** [comment]
Hi,

We are not working on FCOS builds of OKD any more. Please see these documents...

https://okd.io/blog/2024/06/01/okd-future-statement
https://okd.io/blog/2024/07/30/okd-pre-release-testing

We will be providing documentation on upgrading clusters from 4.15 FCOS to 4.16 SCOS. In terms of clusters that are older, you may be able to get help from community members, but the amount of institutional knowledge is limited. 

Many thanks,

Jaime

**Comment by SupremeMortal** [comment]
Software RAID from metal3 is [unsupported in OKD](https://docs.okd.io/4.15/post_installation_configuration/bare-metal-configuration.html#the-baremetalhost-spec). If you want to use mdadm raid, you need to create a machine configuration when generating the cluster manifests whilst running the installer.

Put these two files in the `manifests/` directory to get a RAID 1 mirror.
```yaml
variant: openshift
version: 4.15.0
metadata:
  name: 10-master-raid.yaml
  labels:
    machineconfiguration.openshift.io/role: master
boot_device:
  mirror:
    devices:
      - /dev/sda
      - /dev/sdb
```

```yaml
variant: openshift
version: 4.15.0
metadata:
  name: 10-worker-raid.yaml
  labels:
    machineconfiguration.openshift.io/role: worker
boot_device:
  mirror:
    devices:
      - /dev/sda
      - /dev/sdb
```
