### DISCUSSION TITLE
Port 443 and 80 closed after OKD server rebuild

### DISCUSSION THREAD

**Discussion by ALL-SPACE-Anas** [okd-project/okd#2044] [Q&A]
Hi,

I have OKD4.15 deployed on 3 bare-metal servers. I recently had to remove one server and replace with a new one. I gave the new server same IP and hostname as the old one. The server seems to be working just fine for the most part except it doesn't have ports 443 and 80 exposed. As a result, it doesn't communicate with the load-balancer on those ports and any pods running on that server cannot be exposed.

I'm not sure if this is a bug or if I missed some step. These are the steps I followed to add the new server:

1. Boot from Fedora CoreOS.
2. Pass on the ignition file extracted from the cluster for Fedora CoreOS installation.
3. Once boot up, use below manifest to add the node to the cluster `oc create -f masterX.yaml`.
```
apiVersion: v1
kind: Node
metadata:
  annotations:
    k8s.ovn.org/host-cidrs: '["<host_IP>/24"]'
    k8s.ovn.org/l3-gateway-config: '{"default":{"mode":"shared","interface-id":"br-ex_master#.domain.com","mac-address":"<host_MAC_address>","ip-addresses":["<host_IP>/24"],"ip-address":"<host_IP>/24","next-hops":["#####"],"next-hop":"#####","node-port-enable":"true","vlan-id":"0"}}'
    k8s.ovn.org/remote-zone-migrated: master#.domain.com
    k8s.ovn.org/zone-name: master#.domain.com
    machineconfiguration.openshift.io/controlPlaneTopology: HighlyAvailable
  labels:
    node-role.kubernetes.io/control-plane: ""
    node-role.kubernetes.io/master: ""
    node-role.kubernetes.io/worker: ""
  name: master#.domain.com
spec: {}
```
4. If pending certificates, approve with `oc get csr -o go-template='{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}' | xargs oc adm certificate approve`.
5. Check if etcd pods for the new node are available with `oc -n openshift-etcd get pods -l k8s-app=etcd`.

the node shows as healthy and ready but port scan shows 443 and 80 isn't open.

I've tried rebooting multiple times and manually opening the ports using `iptables` but nothing seems to work. Please let me know if I should share further info and any potential solutions.

Thanks
