### DISCUSSION TITLE
OKD 4.x Install Fails Despite DNS Resolution from Bootstrap Node success

### DISCUSSION THREAD

**Discussion by shashankmotruri** [okd-project/okd#2134] [General]
I am installing OKD on Google Cloud Platform (GCP) using a preconfigured VPC network. For the domain setup, I have delegated a GCP subdomain to an AWS Route 53 main hosted zone. According to the documentation, the OKD installer "creates records in a pre-existing public zone." I have a pre-existing public DNS-managed zone in GCP delegated to AWS Route 53. The records were updated in this zone by the OKD installer as mentioned [here](https://docs.okd.io/4.13/post_installation_configuration/configuring-private-cluster.html#private-clusters-about_configuring-private-cluster).

I was able to resolve the host from the bootstrap node.

````
[core@okd-cluster-gh848-bootstrap ~]$ curl -k https://api.okd-cluster.okd.dev.example.com:6443/version
{
  "major": "1",
  "minor": "30+",
  "gitVersion": "v1.30.6-dirty",
  "gitCommit": "5a24e858060a609366c5ff1402ec1424e9f7e403",
  "gitTreeState": "dirty",
  "buildDate": "2024-11-19T02:46:50Z",
  "goVersion": "go1.22.7 (Red Hat 1.22.7-1.el9_5) X:strictfipsruntime",
  "compiler": "gc",
  "platform": "linux/amd64"
}

````

But, surprisingly, the OKD installation failed to resolve the host

````
DEBUG E0419 17:08:31.945864 1721882 controller.go:324] "Reconciler error" err="failed to get client: failed to create cluster accessor: error creating http client and mapper for remote cluster \"openshift-cluster-api-guests/okd-cluster-gh848\": error creating client for remote cluster \"openshift-cluster-api-guests/okd-cluster-gh848\": cluster is not reachable: Get \"https://api.okd-cluster.okd.dev.example.com:6443/?timeout=5s\": dial tcp: lookup api.okd-cluster.okd.dev.example.com on 100.100.100.100:53: no such host" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" Machine="openshift-cluster-api-guests/okd-cluster-gh848-master-2" namespace="openshift-cluster-api-guests" name="okd-cluster-gh848-master-2" reconcileID="457f696c-c9d4-48d1-a34d-03ea72131ee2"

DEBUG E0419 17:08:43.501025 1721882 controller.go:324] "Reconciler error" err="failed to get client: failed to create cluster accessor: error creating http client and mapper for remote cluster \"openshift-cluster-api-guests/okd-cluster-gh848\": error creating client for remote cluster \"openshift-cluster-api-guests/okd-cluster-gh848\": cluster is not reachable: Get \"https://api.okd-cluster.okd.dev.example.com:6443/?timeout

````

OKD install config used: 

````
  apiVersion: v1
  baseDomain: okd.dev.example.com
  credentialsMode: Manual
  metadata:
    name: okd-cluster
  platform:
    gcp:
      projectID: <project>
      region: us-east1
      network: okd-vpc
      controlPlaneSubnet: okd-subnet
      computeSubnet: okd-subnet
      defaultMachinePlatform:
        serviceAccount: okd-sa@openshift.iam.gserviceaccount.com
  pullSecret: '{"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}}'
  sshKey: <sshKey>
  controlPlane:
    name: master
    replicas: 3
    hyperthreading: Enabled
    platform:
      gcp:
        type: n2-standard-8
  compute:
    - name: worker
      replicas: 6
      hyperthreading: Enabled
      platform:
        gcp:
          type: n2-standard-8
  networking:
    networkType: OVNKubernetes
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    serviceNetwork:
      - 172.30.0.0/16
    machineNetwork:
      - cidr: 10.0.0.0/24

````
Verions: 
openshift-install 4.17.0-okd-scos.0
