### DISCUSSION TITLE
[Upgrade to OKD SCOS 4.19] Network Operator upgrade stuck due to change in the addtionalNetworks handling

### DISCUSSION THREAD

**Discussion by manfuin** [okd-project/okd#2209] [General]
Hi! 

We are facing the upgrade issue from 4.18 to 4.19.

Our Network operator config defines `additionalNetworks` and always looks like this starting from OKD 4.5: 

```yaml
spec:
  additionalNetworks:
  - name: blue-network
    namespace: namespace1
    rawCNIConfig: '{ "cniVersion": "0.3.1", "name": "blue-network", "type": "macvlan",
      "master": "blue0", "ipam": { "type": "whereabouts", "range": "<range1>",
      "routes": [<routes>] } }'
    type: Raw
  - name: blue-network
    namespace: namespace2
    rawCNIConfig: '{ "cniVersion": "0.3.1", "name": "blue-network", "type": "macvlan",
      "master": "blue0", "ipam": { "type": "whereabouts", "range": "<range2>",
      "routes": [<routes>] } }'
    type: Raw
  - name: blue-network
    namespace: namespace3
    rawCNIConfig: '{ "cniVersion": "0.3.1", "name": "blue-network", "type": "macvlan",
      "master": "blue0", "ipam": { "type": "whereabouts", "range": "<range3>",
      "routes": [<routes>] } }'
    type: Raw
 ...
```

During upgrade to 4.19 the log of Network Operator indicates the following error:

```
E0612 18:19:50.818678       1 base_controller.go:279] "Unhandled Error" err=<
        cluster-network-operator-ManagementState reconciliation failed: unable to extract network operator configuration: error converting obj to typed: errors:
          .spec.additionalNetworks: duplicate entries for key [name="blue-network"]
          .spec.additionalNetworks: duplicate entries for key [name="blue-network"]
          .spec.additionalNetworks: duplicate entries for key [name="blue-network"]
          .spec.additionalNetworks: duplicate entries for key [name="blue-network"]
          .spec.additionalNetworks: duplicate entries for key [name="blue-network"]
          .spec.additionalNetworks: duplicate entries for key [name="blue-network"]
          .spec.additionalNetworks: duplicate entries for key [name="blue-network"]
          .spec.additionalNetworks: duplicate entries for key [name="green-network"]
          .spec.additionalNetworks: duplicate entries for key [name="green-network"]
          .spec.additionalNetworks: duplicate entries for key [name="green-network"]
          .spec.additionalNetworks: duplicate entries for key [name="green-network"]
          .spec.additionalNetworks: duplicate entries for key [name="green-network"]
          .spec.additionalNetworks: duplicate entries for key [name="green-network"]
          .spec.additionalNetworks: duplicate entries for key [name="green-network"]
```

I assume someone forces the name attribute to be unique for each object in the list of additionalNetworks. 

I don't think this is appropriate. 
All these entries transforms to `NetworkAttachmentDefinition` in the different namespaces.

And it is very common and very useful to name `NetworkAttachmentDefinition` the same in the different namespaces for consistency, instead of being forced to assign different names just because of the artificial limits of Network Operator.

It this a known issue? 
Any fix exists/planned?

Kind regards,
Andrii
