### DISCUSSION TITLE
Unable to Install `kubernetes-nmstate-operator` on OKD4.15 Bare Metal Cluster – constraints not satisfiable Error

### DISCUSSION THREAD

**Discussion by ALL-SPACE-Anas** [okd-project/okd#2213] [Q&A] [answered]
I'm attempting to install the kubernetes-nmstate-operator in my OKD 4.15 bare metal cluster, but I'm encountering issues with the operator not resolving correctly through Operator Lifecycle Manager (OLM). I'm following the documentation here: https://docs.okd.io/4.15/networking/k8s_nmstate/k8s-nmstate-about-the-k8s-nmstate-operator.html#installing-the-kubernetes-nmstate-operator-CLI_k8s-nmstate-operator

It doesn't help that the operator isn't available when trying to install from webUI.

I couldn't create a subscription on `redhat-operator` source (understandably) so created a subscription with `community-operators`:
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubernetes-nmstate-operator
  namespace: openshift-nmstate
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kubernetes-nmstate-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
```
The community-operators CatalogSource is healthy according to the Subscription status. However, the operator never installs. The Subscription status shows the following error:

> message: 'constraints not satisfiable: no operators found in package kubernetes-nmstate-operator
in the catalog referenced by subscription kubernetes-nmstate-operator, subscription exists'
reason: ConstraintsNotSatisfiable
type: ResolutionFailed

So, some questions,

- I'm trying to install it as a requisite for OKD virtualization. Does OKD support installing the kubernetes-nmstate-operator from community-operators, or is this operator only available via Red Hat’s certified catalog?
- If community-operators doesn't include it, what is the recommended way to deploy this operator on OKD? Should I use https://github.com/nmstate/kubernetes-nmstate? Anything in particular I need to keep in mind when deploying it from kubernetes-nmsate repo?
- Is there an upstream Helm chart or manifest bundle I should use?
- Are there any OKD-specific limitations or recommendations around using this operator in bare metal environments?
