### DISCUSSION TITLE
Change Cluster Configuration - "baseDomain" and "metadata -> name"

### DISCUSSION THREAD

**Discussion by eduardolucioac** [okd-project/okd#738] [Q&A] [answered]
I installed a cluster with the settings below.

**QUESTION:** Is it possible to modify the settings regarding the attributes "baseDomain" and "metadata -> name" after the cluster has been installed? If yes, how?

**NOTES:**
I - The goal is to make the whole cluster answer calls in a new (sub)domain modified in the attributes "baseDomain" and "metadata -> name";
II - Of course, I will also update the DNS to reflect these changes.

**Thanks! =D**

```
apiVersion: v1
baseDomain: okd.local
metadata:
  name: mbr

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"fake":{"auth": "bar"}}}'
sshKey: '<SSH_PUB_KEY>'
```
