### DISCUSSION TITLE
Version 4.7.0-0.okd-2021-07-17-044921 gone missing from stable-4.7

### DISCUSSION THREAD

**Discussion by bo0ts** [okd-project/okd#788] [Q&A]
**Describe the bug**

On of our OKD 4.7 clusters recently updated to OKD `4.7.0-0.okd-2021-07-17-044921` from the channel `stable-4.7` and the upstream `https://amd64.origin.releases.ci.openshift.org/graph`. 

This version seems to have disappeared leaving the cluster with a warning and it is now unable to upgrade.

How to fix this?

Here is a snippet of our clusterversion:

```
spec:
  channel: stable-4.7
  clusterID: 327da6f1-d8f5-4503-9873-25ee9d55101c
  desiredUpdate:
    image: >-
      registry.ci.openshift.org/origin/release@sha256:cf6801292e8ce41d6678eb9673baecb5c88f2883948185b1e8710b442ef7dbdb
    version: 4.7.0-0.okd-2021-07-17-044921
  upstream: 'https://amd64.origin.releases.ci.openshift.org/graph'
status:
  availableUpdates: null
  conditions:
    - lastTransitionTime: '2021-07-14T05:46:29Z'
      message: Done applying 4.7.0-0.okd-2021-07-17-044921
      status: 'True'
      type: Available
    - lastTransitionTime: '2021-07-23T05:06:01Z'
      status: 'False'
      type: Failing
    - lastTransitionTime: '2021-07-20T09:50:58Z'
      message: Cluster version is 4.7.0-0.okd-2021-07-17-044921
      status: 'False'
      type: Progressing
    - lastTransitionTime: '2021-07-24T12:36:19Z'
      message: >-
        Unable to retrieve available updates: currently reconciling cluster
        version 4.7.0-0.okd-2021-07-17-044921 not found in the "stable-4.7"
        channel
      reason: VersionNotFound
      status: 'False'
      type: RetrievedUpdates
```

**Version**

`4.7.0-0.okd-2021-07-17-044921`

**How reproducible**

I cannot reproduce this, since the update that caused it is not available anymore.
