### DISCUSSION TITLE
Configuring and using LDAP - "error: x509: certificate signed by unknown authority"

### DISCUSSION THREAD

**Discussion by eduardolucioac** [okd-project/okd#797] [Q&A] [answered]
Hi everyone! It's me again!

We are trying to configure OpenShift (OKD) to consume our LDAP for the authentication process.

Our LDAP directory does not require authentication ("bindPassword", "secret"). It is also not an LDAPS and therefore does not need a certificate ("configmap").

In view of the above, we are configuring access via LDAP as shown below...

```
cat <<EOF | oc apply -f -
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: ldapidp
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        id:
        - dn
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: ""
      insecure: true
      url: "ldap://10.2.0.5:389/dc=somedm,dc=abc,dc=xy?uid"
EOF
```

However, when we try to use a valid user the following error happens...

```
[root@okd-services ~]# oc login -u someuser
error: x509: certificate signed by unknown authority
```

**What could be going wrong?**

We are following these guidelines: https://docs.okd.io/latest/authentication/identity_providers/configuring-ldap-identity-provider.html

[]'s
