### ISSUE TITLE
4.9 OVNKubernetes Bugs working with external ips

### ISSUE THREAD

**Issue by codecap** [okd-project/okd#1143]
**Describe the bug**
After Installing OKD 4.9 we expected several issues with OVNKubernetes regarding external-ips

I reported the issues here:
https://github.com/ovn-org/ovn-kubernetes/issues/2853
https://github.com/ovn-org/ovn-kubernetes/issues/2854

Service Type LoadBalancer with Autoassigned external is not reachable
All Nodes answer to request to external ip (although they should not according to the documentation)

**Version**
We observed the bug atleast in the versions
4.9.0-0.okd-2022-01-29-035536
4.9.0-0.okd-2022-02-12-140851

**How reproducible**
Described in the bug reports listed above
100% reproducible

**Comment by vrutkovs** [comment]
Lets file an OCP bugzilla for these, so that we could track which branch does this land and when it gets promoted to OKD

**Comment by codecap** [comment]
Hi!

I just tested it with 4.10.0-0.okd-2022-03-07-131213, the bugs seems not to be there.

External IPs work as expected.

So it seems to be connected with 4.9 builds, or how can you explain this ?

**Comment by tonymalynn9** [comment]
Running into this issue on `4.9.0-0.okd-2022-02-12-140851` and `4.10.0-0.okd-2022-03-07-131213`

`4.9.0-0.okd-2022-02-12-140851 network config`
```
apiVersion: config.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  externalIP:
    autoAssignCIDRs:
      - XX.XX.XX.0/24
    policy:
      allowedCIDRs:
        - XX.XX.XX.0/24
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16
status:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  clusterNetworkMTU: 1400
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16
```

`4.10.0-0.okd-2022-03-07-131213 network config`
```
apiVersion: config.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  externalIP:
    autoAssignCIDRs:
      - XX.XX.XX.0/24
    policy:
      allowedCIDRs:
        - XX.XX.XX.0/24
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16
status:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  clusterNetworkMTU: 1400
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16
 ```

Essentially identical except for the CIDR.

When creating a Service type LoadBalancer an ExternalIP is assigned but does not work.
However, when I add a second ExternalIP to the service both ExternalIPs will work.

Is there a waiting period for the first IP to start working?
