### ISSUE TITLE
Change of OAuth URL not working as expected

### ISSUE THREAD

**Issue by devops-42** [okd-project/okd#1326]
**Describe the bug**
We use custom certificates for our OKD clusters in multiple environments. Therefore we tried to adapt the oauth-url from something like `oauth-openshift.apps.<our.base.domain.tld>` to `oauth-openshift.<our.base.domain.tld>` according to the documentation https://docs.okd.io/latest/authentication/configuring-internal-oauth.html#customizing-the-oauth-server-url_configuring-internal-oauth.
Side note: We have a custom console URL configured too (using our certificate).

Steps we've done see below in "How reproducable"

The outcome was, that:
- Our custom console route lost it's certificates (reverted back to the default ingress)
- The authentication pods stuck in `ContainerCreating` because of a missing secret: 
```
MountVolume.SetUp failed for volume "v4-0-config-system-router-certs" : secret "v4-0-config-system-router-certs" not found
```
The OAuth and the console operators got degraded.

Question: Is there a possibility to get the domain changed (i.e. to remove the `apps` sub-domain)?

Thanks in advance for your help and comments!

**Version**
4.11.0-0.okd-2022-08-20-022919

**How reproducible**
Follow the documentation (linked above):
1. Create a TLS secret in namespace `openshift-config`
2. Edit the Ingress object `cluster` by using `oc edit ingress.config.openshift.io cluster`
```
apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  name: cluster
spec:
  componentRoutes:
    - name: oauth-openshift
      namespace: openshift-authentication
      hostname: oauth-openshift.<our.base.domain.tld>
      servingCertKeyPairSecret:
        name: <secret_name> 
```

We tried to change add the `domain` key and set it to `<our.base.domain.tld>` but without success.
