### ISSUE TITLE
4.10.0-0.okd-2022-07-09-073606 ingress with pathType: Exact can not generate route

### ISSUE THREAD

**Issue by KevinChu148** [okd-project/okd#1469]
Hello,

As I know "Route should be created automatically when I create ingress". 
I found:  ingress with "pathType: Exact" can not generate route.

**Describe the bug:**
-Create new project
`oc new-project test`

-Create new app
`oc new-app openshift/hello-openshift`

-Then created Ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-openshift
spec:
  rules:
  - host: hello.example.com
    http:
      paths:
      - backend:
          service:
            name: hello-openshift
            port:
              number: 8080
        path: /
        pathType: Exact

```
-Get route
`oc get route  -n test`
**No resources found in test namespace.**
If I change pathType: Exact to pathType: Prefix, route will generate normal.
