### ISSUE TITLE
Masters not upgrading, authentication/Ingress Operator degraded after upgrading from 4.10.0-0.okd-2022-07-09-073606 to 4.11.0-0.okd-2023-01-14-152430

### ISSUE THREAD

**Issue by danielchristianschroeter** [okd-project/okd#1474]
**Describe the bug**
After upgrading my vSphere IPI installation from from version 4.10.0-0.okd-2022-07-09-073606 to 4.11.0-0.okd-2023-01-14-152430 the Ingress operator seems to be unstable. The console UI for example is also only sometimes available.
It started with this error in the authentication operator here:
OAuthServerRouteEndpointAccessibleControllerDegraded: Get \"https://oauth-openshift.apps.okd-01.domain.tld/healthz\": dial tcp 10.1.233.5:443: connect: connection refused\nProxyConfigControllerDegraded: failed to reach endpoint

**Version**
from 4.10.0-0.okd-2022-07-09-073606 to 4.11.0-0.okd-2023-01-14-152430

**Log bundle**
https://drive.google.com/file/d/1ZTdYqMPeHcOPXnhUGbdd_XWMmTvapNWk/view?usp=sharing

**Comment by melledouwsma** [comment]
The master MachineConfigPool won't upgrade because it is degraded. From `oc get mcp master -o yaml`:

```yaml
status:
  conditions:
  - lastTransitionTime: '2023-01-21T21:42:58Z'
    message: 'Node okd-01-zvldl-master-1 is reporting: "unexpected on-disk state validating
      against rendered-master-4faba702afb193239685ebe1c5c7a053: Missing expected kernel
      arguments: [mitigations=off intel_pstate=disable]", Node okd-01-zvldl-master-0
      is reporting: "unexpected on-disk state validating against rendered-master-4faba702afb193239685ebe1c5c7a053:
      Missing expected kernel arguments: [mitigations=off intel_pstate=disable]",
      Node okd-01-zvldl-master-2 is reporting: "unexpected on-disk state validating
      against rendered-master-4faba702afb193239685ebe1c5c7a053: Missing expected kernel
      arguments: [mitigations=off intel_pstate=disable]"'
    reason: 3 nodes are reporting degraded status on sync
    status: 'True'
    type: NodeDegraded
```

Could this be related to https://github.com/okd-project/okd/issues/1013, where removing those mc's will resolve that difference?
