### ISSUE TITLE
4.11.0-0.okd-2023-01-21-111419 Kubelet cpu and memory hungry with cgroupv2

### ISSUE THREAD

**Issue by ExNG** [okd-project/okd#1479]
**Describe the bug**

Kubeletes on OKD 4.11 are running high on CPU and eating up memory, correlating with number of pods started on their node. This leads to nodes being unready and not recovering, even over weekends, where only a hard reboot helps.\
The cluster runs on 4.11.0-0.okd-2023-01-21-111419 with only cgroup v2 enabled and has barely any workload.

Here is a screenshot of a node with a stable growth of cpu without new pod activity:
![image](https://user-images.githubusercontent.com/24767736/214322424-5147494a-cbf2-4635-964d-a23dde5c3b69.png)

And here the kubelet service only:
![image](https://user-images.githubusercontent.com/24767736/214324325-38b6f053-d4d0-4df9-ac93-75b4bb660403.png)

Also the memory usage of kubelet over the same time period:
![image](https://user-images.githubusercontent.com/24767736/214324399-7f9fa378-4bbf-4bd4-b9ec-a9a525ebddc5.png)

As you can see in the afternoon memory usage somewhat stabilized after applying the recommended cleaner daemonset from #1310.
I am not sure this workaround is stable or even fit for production.

**Version**

4.11.0-0.okd-2023-01-21-111419
UPI on VSphere

**How reproducible**
100%
NOTE: This issue appears after a certain amount of time but can be summoned by starting a lot of pods on the same node. 

**Log bundle**

https://clouddrive.avm.de/s/Cyzjo47AkkPAX2N
PW: v8I06gVNyp

**Comment by ExNG** [comment]
I tried to dig deeper and it seems like the kubelet tries to export metrics of removed pods.
See the two go pprof visuals below, left is before and right after the cleanup DS ran:

| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24767736/214330559-b5e79c88-1cf5-4e33-aedb-3476f1681772.png) | ![image](https://user-images.githubusercontent.com/24767736/214330623-ae9ec4e5-b40d-49e1-822c-1df295787caa.png) |

Note that manager housekeeping has dropped by ~700. 
Also in the profile visual visable is that that http runHandler time drops in half


| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24767736/214332386-c23701e9-e7ce-4dc3-be2e-d1ea0f7d7315.png) | ![image](https://user-images.githubusercontent.com/24767736/214332429-5f300ecf-5f1d-43aa-811a-cff5afc2b0a7.png) |

**Comment by ExNG** [comment]
It seems to be a similar issue at https://github.com/kubernetes/kubernetes/issues/106957 and https://github.com/cri-o/cri-o/issues/6349, both of which are currently active

**Comment by ExNG** [comment]
Hi @vrutkovs i havent tested 4.12 but i can give you the cronjob of evil:
```yaml
kind: CronJob
apiVersion: batch/v1
metadata:
  name: example
  namespace: default
spec:
  schedule: '* * * * *'
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: 'docker.io/library/busybox:latest'
              args:
                - /bin/sh
                - '-c'
                - date; echo Hello from the Kubernetes cluster
            - name: hello2
              image: 'docker.io/library/busybox:latest'
              args:
                - /bin/sh
                - '-c'
                - date; echo Hello from the Kubernetes cluster
            - name: hello3
              image: 'docker.io/library/busybox:latest'
              args:
                - /bin/sh
                - '-c'
                - date; echo Hello from the Kubernetes cluster
            - name: hello4
              image: 'docker.io/library/busybox:latest'
              args:
                - /bin/sh
                - '-c'
                - date; echo Hello from the Kubernetes cluster
            - name: hello5
              image: 'docker.io/library/busybox:latest'
              args:
                - /bin/sh
                - '-c'
                - date; echo Hello from the Kubernetes cluster
           
```
