### ISSUE TITLE
OKD SNO Bootstrap In Place fails to properly set the boot priority to boot from the Install Device

### ISSUE THREAD

**Issue by cgruver** [okd-project/okd#1605]
**Describe the bug**
__Note:__ This is attempting an unattended, no-touch, install via iPXE.  This method does not use the assisted installer and boot from an attached ISO.

This install method is using two internal disks.  The first is the initial boot disk, the second is the install disk.

The installation is successful.  However, upon completion of the FCOS install to the `install disk` the EFI boot priority is still preferring the initial boot disk first.  So, on reboot the machine does not boot from the proper disk without manual intervention.

After changing the boot priority, the machine continues to install OKD successfully.

**Version**
`4.12.0-0.okd-2023-04-16-041331`

**How reproducible**
100%

**Comment by cgruver** [comment]
Install Config:

```yaml
apiVersion: v1
baseDomain: my.awesome.lab
metadata:
  name: okd4-sno-1
networking:
  networkType: OVNKubernetes
  clusterNetwork:
  - cidr: 10.88.0.0/14
    hostPrefix: 23 
  serviceNetwork: 
  - 172.20.0.0/16
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 1
platform:
  none: {}
pullSecret: '{"auths": {"fake": {"auth": "Zm9vOmJhcgo="}}}'
sshKey: ssh-rsa AAAAB3NzaC1...
BootstrapInPlace:
  InstallationDisk: "/dev/sda"
```
