### ISSUE TITLE
OKD SNO Bootstrap In Place fails to pass network configuration to final OS install

### ISSUE THREAD

**Issue by cgruver** [okd-project/okd#1606]
**Describe the bug**
Note: This is attempting an unattended, no-touch, install via iPXE. This method does not use the assisted installer and boot from an attached ISO.

This install method is using two internal disks. The first is the initial boot disk, the second is the install disk.

I am giving the machine static network information.  The same information is passed via kargs, and ignition.

During the first phase of install, the system is using the correct network configuration.  But, after pivoting to boot from the install disk, it has reverted to DHCP.  The only way to complete the install is to configure an IP reservation for the duration of the install, and then apply a MachineConfig with the correct network configuration after the install is complete.

**Version**
`4.12.0-0.okd-2023-04-16-041331`

**How reproducible**
100%

**Comment by cgruver** [comment]
iPXE boot file:

```bash
#!ipxe

kernel http://10.11.12.1/install/fcos/4.12.0-0.okd-2023-04-16-041331/vmlinuz edd=off net.ifnames=1 ifname=nic0:48:21:0b:50:b6:d7 ip=10.11.12.60::10.11.12.1:255.255.255.0:okd4-sno-1-node.my.awesome.lab:nic0:none nameserver=10.11.12.1 rd.neednet=1 coreos.inst.install_dev=/dev/nvme0n1 coreos.inst.ignition_url=http://10.11.12.1/install/fcos/ignition/okd4-sno-1.my.awesome.lab/48-21-0b-50-b6-d7.ign coreos.inst.platform_id=metal initrd=initrd initrd=rootfs.img 
initrd http://10.11.12.1/install/fcos/4.12.0-0.okd-2023-04-16-041331/initrd
initrd http://10.11.12.1/install/fcos/4.12.0-0.okd-2023-04-16-041331/rootfs.img

boot
```

**Comment by cgruver** [comment]
Butane YAML used to modify the ignition file generated by `openshift-install create single-node-ignition-config`

```yaml
variant: fcos
version: 1.4.0
ignition:
  config:
    merge:
      - local: sno.ign
storage:
  files:
    - path: /etc/zincati/config.d/90-disable-feature.toml
      mode: 0644
      contents:
        inline: |
          [updates]
          enabled = false
    - path: /etc/systemd/network/25-nic0.link
      mode: 0644
      contents:
        inline: |
          [Match]
          MACAddress=48:21:0b:50:b6:d7
          [Link]
          Name=nic0
    - path: /etc/NetworkManager/system-connections/nic0.nmconnection
      mode: 0600
      overwrite: true
      contents:
        inline: |
          [connection]
          type=ethernet
          interface-name=nic0

          [ethernet]
          mac-address=48:21:0b:50:b6:d7

          [ipv4]
          method=manual
          addresses=10.11.12.60/24
          gateway=10.11.12.1
          dns=10.11.12.1
          dns-search=my.awesome.lab
    - path: /etc/hostname
      mode: 0420
      overwrite: true
      contents:
        inline: |
          okd4-sno-1-node.my.awesome.lab
    - path: /etc/chrony.conf
      mode: 0644
      overwrite: true
      contents:
        inline: |
          pool 10.11.12.1 iburst 
          driftfile /var/lib/chrony/drift
          makestep 1.0 3
          rtcsync
          logdir /var/log/chrony
```
