### ISSUE TITLE
OKD 4.13 - Cluster operator machine-config should not be upgraded between minor versions

### ISSUE THREAD

**Issue by cronchiq** [okd-project/okd#1617]
**Describe the bug**

**Version**
Upgrade from 4.12.0-0.okd-2023-04-16-041331 to 4.13.0-0.okd-2023-05-22-052007

**How reproducible**
Upgrade to 4.13.0-0.okd-2023-05-22-052007

**Log bundle**

Must-gather: https://drive.google.com/file/d/1gmao7l7nyzQkfpWYtntkg1QLnO0vxGey/view?usp=sharing

**Comment by vrutkovs** [comment]
I see you have
```
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 51-master-kernel-devel
spec:
  extensions:
  - kernel-devel
```

Do you have Fedora repos enabled to fetch new kernel-devel and additional packages?
