### ISSUE TITLE
Remove Storage Cluster Operator

### ISSUE THREAD

**Issue by jvincze84** [okd-project/okd#1641]
Dear All,

We need some help about the Storage Cluster Operator.
We installed our OKD cluster 2020 starting with "4.5.0-0.okd-2020-07-14-153706-ga" version.
The current version is "4.12.0-0.okd-2023-04-16-041331". 

All of our nodes are user provisoned, and we don't use the cluster auto scaler.

We chose vSphere platform in the install-config.yaml.

Example:
```
platform:
  vsphere:
    vcenter: example.vceneter.hu
    username: okduser
    password: okdtest
    datacenter: dc01
    defaultDatastore: defaultds
```

Starting from version 4.11 the storage operator trying to access our vSphere cluster, but the user don't have the right privileges (system.read), for the action, and we are unable to give access because of security reasons.

Since the operator is failing, the update process could be blocked. We tried to set the operator to "Unmanaged", but it does not help much.

My question is:
Is there any way to completely remove/delete/turn off this Storage Cluster Operator? 
(Reinstalling the entire cluster is not an option.)

Thanks a lot,
Jvincze84
