### ISSUE TITLE
Image Registry configuration patch isn't applied when adding `allowedRegistries`

### ISSUE THREAD

**Issue by ProtossGP32** [okd-project/okd#1645]
**Describe the bug**

I'd llke to add the internal registry as an additional registry where to pull images from when launching Builds (for example, to not depend on docker pull quotas). For that, I've followed the steps in [the official docs](https://docs.okd.io/latest/openshift_images/image-configuration.html#images-configuration-file_image-configuration), but after finished patching the `image.config.openshift.io/cluster` custom resource, the nodes aren't cordoned and the changes only remain in there, there's no rollout of it.

**Version**

OKD version release: 4.13.0-0.okd-2023-05-22-052007
Install method: IPI
Cloud platform: OpenStack

**How reproducible**

100%, just follow the instructions in [the official docs](https://docs.okd.io/latest/openshift_images/image-configuration.html#images-configuration-file_image-configuration) to add the internal registry as an `allowedRegistries` entry:
```
oc edit image.config.openshift.io/cluster
```
And then adding the list of allowed registers:
```yaml
 apiVersion: config.openshift.io/v1
 kind: Image
 [...]
 spec:
   registrySources:
     allowedRegistries:
     - image-registry.openshift-image-registry.svc:5000
     - quay.io
     - registry.redhat.io
     - docker.io
```

**Expected behaviour**
Nodes are cordoned, new config is applied and nodes are uncordoned again. I'd expect to see the `NotReady` status in the nodes for some amount of time.

**Real behaviour**
Nodes aren't cordoned at all, they keep on being `Ready`; the custom resource is modified (checked again with `oc get image.config.openshift.io/cluster -o yaml`) and thus there's no rollout of the changes in the platform.

**Log bundle**
