### ISSUE TITLE
Error updating node status

### ISSUE THREAD

**Issue by balait4** [okd-project/okd#1758]
Suddenly few worked nodes(everytime same set of worker nodes) goes into `NotReady` state and which back to normal themselves in 40 mins time. During this time I'm able to ping the pod from this issue nodes and also external url resolves fine(so network seems fine). The master nodes resources are fine too. I tried rebooting the issue node, tried restarting the kube-apiserver, tried restarting kubelet services which didn't help. Around 40 mins it was there and then it automatically get resolves. 
We are worried this is production nodes which is having this unexpected issue monthly 2 or 3 times randomly. 

We are facing this strange Behaviour not only in 4.13 we recently upgraded but also in 4.12 version. So this seems not related to the okd version, but not sure how to exactly find the root cause of this issue. Appreciate. any help on this. 

```
Oct 10 00:45:20 db-1 kubenswrapper[2851]: E1010 00:45:20.016318    2851 kubelet_node_status.go:567] "Error updating node status, will retry" err="error getting
node \"db-1-fsn-eu.k8sprod.targomo.com\": Get \"https://api-int.com:6443/api/v1/nodes/db-1-fsn-eu.com?resourceVersion=0&timeout=10s\": net/http: request ca
nceled (Client.Timeout exceeded while awaiting headers)"
```
I added the must-gatherlogs in the below link. 
https://drive.google.com/file/d/1cb7yJ0_SaarCVy9UVynhy0MHc9pzIEPb/view?usp=drive_link

**Comment by vrutkovs** [comment]
Seems `api-int` load balancer is not reachable? 

Pod connectivity checks saw various outages basically every month, ranging from few seconds to several days in September:
```
    outages:
    - end: "2023-09-23T17:10:22Z"
      endLogs:
      - latency: 12.991728ms
        message: 'load-balancer-api-internal: tcp connection to api-int.k8sprod.targomo.com:6443
          succeeded'
        reason: TCPConnect
        success: true
        time: "2023-09-23T17:10:22Z"
...
      - latency: 9.999016129s
        message: 'load-balancer-api-internal: failed to establish a TCP connection
          to api-int.k8sprod.targomo.com:6443: dial tcp 216.59.63.2:6443: i/o timeout'
        reason: TCPConnectError
        success: false
        time: "2023-09-20T01:13:27Z"
      message: Connectivity restored after 87h56m55.720371258s
```

Since its baremetal install you certainly should check the network setup
