### ISSUE TITLE
openshift-apiserver CrashLoopBackOff Context deadline exceeded

### ISSUE THREAD

**Issue by mreiche** [okd-project/okd#1764]
**Describe the bug**
`openshift-apiserver` Deployment Pod stays in CrashLoopBackOff on Master Node (after upgrade)

Pod log
```
stdout F Copying system trust bundle
stderr F I1018 08:18:07.235364       1 dynamic_serving_content.go:112] "Loaded a new cert/key pair" name="serving-cert::/var/run/secrets/serving-cert/tls.crt::/var/run/secrets/serving-cert/tls.key"
stderr F I1018 08:18:07.679594       1 requestheader_controller.go:244] Loaded a new request header values for RequestHeaderAuthRequestController
stderr F I1018 08:18:07.682230       1 audit.go:353] Using audit backend: ignoreErrors<log>
stderr F I1018 08:18:07.683668       1 plugins.go:84] "Registered admission plugin" plugin="NamespaceLifecycle"
stderr F I1018 08:18:07.683691       1 plugins.go:84] "Registered admission plugin" plugin="ValidatingAdmissionWebhook"
stderr F I1018 08:18:07.683696       1 plugins.go:84] "Registered admission plugin" plugin="MutatingAdmissionWebhook"
stderr F I1018 08:18:07.684208       1 admission.go:48] Admission plugin "project.openshift.io/ProjectRequestLimit" is not configured so it will be disabled.
stderr F I1018 08:18:07.684954       1 plugins.go:158] Loaded 5 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,build.openshift.io/BuildConfigSecretInjector,image.openshift.io/ImageLimitRange,image.openshift.io/ImagePolicy,MutatingAdmissionWebhook.
stderr F I1018 08:18:07.684971       1 plugins.go:161] Loaded 9 validating admission controller(s) successfully in the following order: OwnerReferencesPermissionEnforcement,build.openshift.io/BuildConfigSecretInjector,build.openshift.io/BuildByStrategy,image.openshift.io/ImageLimitRange,image.openshift.io/ImagePolicy,quota.openshift.io/ClusterResourceQuota,route.openshift.io/RequiredRouteAnnotations,ValidatingAdmissionWebhook,ResourceQuota.
stderr F F1018 08:18:27.689078       1 openshift_apiserver.go:379] context deadline exceeded
.. [Golang Stacktrace] follows here ..
```

I performed:
- https://docs.openshift.com/container-platform/4.11/support/troubleshooting/troubleshooting-crio-issues.html (No CRIO issues found)
- https://access.redhat.com/solutions/5049001 (No DNS issues found)
- Node Restart

**Version**
`openshift-apiserver` Pod and deployment image: `quay.io/openshift/okd-
content@sha256:0d56d4dd26583f083634881fd02920002c05f7eaa4d3beb464b950c0e52e25ff`
OKD: `4.11.0-0.okd-2023-01-14-152430`

**How reproducible**
Not reproducible at all.

**Log bundle**
(May follow up)

**Comment by mreiche** [comment]
I downgraded the components in `openshift-apiserver-operator`
```yaml
      env:
        - name: IMAGE
          value: >-
            quay.io/openshift/okd-content:4.11.0-0.okd-2022-12-02-145640-openshift-apiserver
        - name: OPERATOR_IMAGE
          value: >-
            quay.io/openshift/okd-content:4.11.0-0.okd-2022-12-02-145640-cluster-openshift-apiserver-operator
        - name: OPERATOR_IMAGE_VERSION
          value: 4.11.0-0.okd-2023-01-14-152430
        - name: OPERAND_IMAGE_VERSION
          value: 4.11.0-0.okd-2023-01-14-152430
        - name: KUBE_APISERVER_OPERATOR_IMAGE
          value: >-
            quay.io/openshift/okd-content:4.11.0-0.okd-2022-12-02-145640-cluster-kube-apiserver-operator
      image: >-
        quay.io/openshift/okd-content:4.11.0-0.okd-2022-12-02-145640-cluster-openshift-apiserver-operator
```

The pod always crashes after 20 seconds. I increased the readiness timeout to 120 second, which also did not help.
