### ISSUE TITLE
[AWS] Cluster failed with: ERROR failed to initialize the cluster: Cluster operators authentication, console, image-registry, ingress, monitoring, storage are not available

### ISSUE THREAD

**Issue by Felice-Copp56** [okd-project/okd#1935]
### Discussed in https://github.com/okd-project/okd/discussions/1934

<div type='discussions-op-text'>

<sup>Originally posted by **Felice-Copp56** April 29, 2024</sup>
Cluster installation fails with following errors: link to https://docs.google.com/document/d/1SSNZvLWmV8eKK8FXkYVs-Ef6PYperIKJ2mmdO6L9w-w/edit?usp=drive_link

**install-config.yaml**
```
apiVersion: v1
baseDomain: dummytest.eu
credentialsMode: Manual
controlPlane:   
  hyperthreading: Enabled 
  name: master
  platform:
    aws:
      iamRole: openshift-ec2-role
      zones:
      - eu-south-1a
      rootVolume:
        iops: 4000
        size: 500
        type: io1 
      metadataService:
        authentication: Optional 
      type: t3.xlarge
  replicas: 1
compute: 
- hyperthreading: Enabled 
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 500
        type: io1 
      metadataService:
        authentication: Optional 
      type: t3a.large
      zones:
      - eu-south-1a
  replicas: 1
metadata:
  name: bper-cluster 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.1.0.0/16
  networkType: OVNKubernetes 
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: eu-south-1 
    propagateUserTags: true 
    userTags:
      adminContact: Felice
    subnets: 
    - subnet-0614e4dc63daa00c6 #private
    - subnet-0f48ac968e2afc137 #public
publish: Internal
fips: false 
pullSecret: 'secrethere'
sshKey: 'sshkeyhere'
``` 

**Version**
4.15.9

**Steps**

- generate a rsa key as explained in red hat guide (https://docs.openshift.com/container-platform/4.15/installing/installing_aws/installing-aws-private.html#ssh-agent-using_installing-aws-private)
- Add key to agent with: `ssh-add <path>/<file_name> `
- create install-config with `./openshift-install create install-config --dir workdir`
- ` ./openshift-install create manifests --dir workdir`
- ` ./openshift-install create cluster --dir workdire --log-level=debug`

**Note**
I have successfully deployed two clusters with the same configuration and options. I have seen them in a ready status on the Red Hat Cloud Cluster dashboard. However, after these two attempts, the clusters no longer work or start
Thanks</div>
