### ISSUE TITLE
Red Hat branding in fresh install on OpenStack

### ISSUE THREAD

**Issue by alexzose** [okd-project/okd#2105]
Installed OKD SCOS 4.17.0-okd-scos.2 with IPI on OpenStack. The oauth-openshift page has Red Hat logo / branding.

The weird thing is that we also had a FCOS variant version 4.15 installed on the same OpenStack environment, which we updated to 4.17 SCOS and the oauth-openshift page does not have this issue.

**Comment by BeardOverflow** [comment]
It is already resolved for 4.18 version, but was not backported to 4.16/4.17 releases.
https://issues.redhat.com/browse/OKD-214
https://github.com/openshift/console-operator/pull/896

As workaround, you can configure the branding avoiding console-operator:
```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  name: console-config
  namespace: openshift-config-managed
data:
  console-config.yaml: |
    kind: ConsoleConfig
    apiVersion: console.openshift.io/v1
    customization:
      branding: okd
      documentationBaseURL: https://docs.okd.io/4.17/
```
