### ISSUE TITLE
OKD 4.15 The addresses of monitoring services are not working

### ISSUE THREAD

**Issue by habibullinrsh** [okd-project/okd#2133]
**Describe the bug**
I am installing OKD 4.15.
Along with it, the cluster-monitoring-operator is installed, to which the minimum number of parameters is passed:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    telemeterClient:
      enabled: false
    enableUserWorkload: true
    prometheusK8s:
      retention: 1d
      volumeClaimTemplate:
        metadata:
          name: openshift-prometheus-pvc
        spec:
          storageClassName: linstor-hdd
          resources:
            requests:
              storage: 20Gi
    alertmanagerMain:
      logLevel: debug
      enabled: true
      volumeClaimTemplate:
        metadata:
          name: openshift-alertmanager-pvc
        spec:
          storageClassName: linstor-hdd
          resources:
            requests:
              storage: 20Gi

```
All services are up and running.
This creates addresses:
 - alertmanager-main-openshift-monitoring.apps.example.com with path /api
 - prometheus-k8s-openshift-monitoring.apps.example.com with path /api
 - prometheus-k8s-federate-openshift-monitoring.apps.example.com with path /federate
 - thanos-querier-openshift-monitoring.apps.example.com with path /api

If I go to any of the addresses, I get "Application is not available". If I click through with the path, I get "404 page not found".
I also noticed that the router settings now specify "routerCanonicalHostname: router-default.apps.example.com ", and in previous versions it was "routerCanonicalHostname: apps.example.com ".

If you delete path from the routes settings and specify "routerCanonicalHostname: apps.example.com ", these are the addresses of the services becoming available.
Can you tell me if this is a bug or do I need to specify some additional parameters?

**Version**
4.15.0-0.okd-2024-03-10-010116
UPI

**How reproducible**
100%

**Log bundle**
I can't send an upload yet without approval from the security department.
