### ISSUE TITLE
Git clone executed in container, makes kubelet unable to start

### ISSUE THREAD

**Issue by Diegunio** [okd-project/okd#2182]
**Backstory of the problem discovery:**
While replacing the IngressController certificates, the kubelet service restarts because the CA (Certificate Authority) of the OpenShift node changes. However, on one of the nodes, the kubelet restart could not complete due to an error stating that one of the emptyDir volumes assigned to a specific pod had incorrect SELinux permissions.

The repository is cloned using the following command:
```bash
git -c http.sslVerify=$GIT_TLS_VERIFY clone --branch "$IT_BRANCH" "$GIT_URL" $TMP_DIR
```
It is cloned and prepared in the initContainer. After the emptyDir is ready, it is transferred to the main container with the built version. The container works normally until the kubelet service restarts. After the restart, the process fails to start due to the emptyDir that contains the cloned Git repository. Specifically, it performs a clone from a private GitLab.

**Version:**
UPI 4.18.0-okd-scos.8
registry.ci.openshift.org/origin/release-scos@sha256:de900611bc63fa24420d5e94f3647e4d650de89fe54302444e1ab26a4b1c81c6

**Issue Behavior:**
The issue always occurs and can be reproduced every time.

**How to reporduce:**
1. Create any container that uses the git clone command and saves the cloned repository data to an emptyDir (make sure to note the node on which the pod is created).

2. Log into the node and execute the following commands:
```bash
systemctl stop kubelet.service
systemctl start kubelet.service
```
The result should be that the kubelet fails to start due to issues with the directory containing the data.

**Example kubelet service log (in practice, this is just one repeating log for various files):**
```bash
Apr 25 08:23:58 worker-4.dev.example.com restorecon[53570]: /var/lib/kubelet/pods/f61afe9e-7fc3-413c-8f61-xd41affe9f73/volumes/kubernetes.io~empty-dir/emptydir-build/node_modules/@mui/icons-material/TerrainSharp.d.ts not reset as customized by admin to system_u:object_r:container_file_t:s0:c5,c35
```

**Troubleshooting performed:**

I checked the security contexts for the emptyDir that causes the issue and one that does not perform the git clone and does not cause any issue. Both directories and files within these directories had exactly the same security contexts, verified using:
ls -lZa
```bash
#Not working
-rw-r--r--. 1 1001200000 1001200000 system_u:object_r:container_file_t:s0:c5,c35 1140 Apr 25 05:42 index.js

#Working
-rw-r--r--. 1 1001200000 1001200000 system_u:object_r:container_file_t:s0:c5,c35   2 Apr 25 05:46 nginx.pid
```

lsattr:
```bash
#Not working
---------------------- indexeddb.js
#Working
---------------------- nginx.pid
```

getfattr -d -m -:
```bash
#Not working
# file: indexeddb.js
security.selinux="system_u:object_r:container_file_t:s0:c5,c35"
#Working
# file: nginx.pid
security.selinux="system_u:object_r:container_file_t:s0:c5,c35"
```

All files in this directory have the same security context (the same one set in the pod under spec.securitycontext.selinuxoptions). I verified this as follows:

```yaml
#Not working
ls -Z emptydir-build | cut -d':' -f5 | sort | uniq
c5,c35 @typescript-eslint
c5,c35 ignore
c5,c35 minimatch
c5,c35 semver

#Working
ls -Z emptydir-tmp | cut -d':' -f5 | sort | uniq
c5,c35 client_temp
c5,c35 fastcgi_temp
c5,c35 nginx.pid
c5,c35 proxy_temp
c5,c35 scgi_temp
c5,c35 uwsgi_temp
```
```yaml 
  securityContext:
    seLinuxOptions:
      level: 's0:c35,c5'
    fsGroup: 1001200000
    fsGroupChangePolicy: Always
    seccompProfile:
      type: RuntimeDefault
```

I tried using spec.volumes.emptydir.medium: Memory in the deployment definition, but the issue still occurred.

I set the most restrictive possible security context in the pod definition, with the SCC set to restricted-v2.

Pod-level securityContext:
```yaml
      securityContext:
        fsGroupChangePolicy: Always
```

initContainer securityContext:
```yaml
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
```

container securityContext:
```yaml
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
```
