### ISSUE TITLE
OKD installation health checks are unhealthy

### ISSUE THREAD

**Issue by shashankmotruri** [okd-project/okd#2183]
**Describe the bug**

Installed OKD from the steps https://docs.okd.io/latest/installing/installing_gcp/installing-gcp-default.html health checks are failing on master nodes during bootstrapping.

````
---
backend: https://www.googleapis.com/compute/v1/projects/yb-openshift-dev/zones/us-east1-b/instanceGroups/okd-95m5h-master-us-east1-b
status:
  healthStatus:
  - forwardingRule: https://www.googleapis.com/compute/v1/projects/yb-openshift-dev/regions/us-east1/forwardingRules/okd-95m5h-api-internal
    forwardingRuleIp: 10.0.0.2
    healthState: UNHEALTHY
    instance: https://www.googleapis.com/compute/v1/projects/yb-openshift-dev/zones/us-east1-b/instances/okd-95m5h-master-0
    ipAddress: 10.0.0.5
    port: 80
  - forwardingRule: https://www.googleapis.com/compute/v1/projects/yb-openshift-dev/regions/us-east1/forwardingRules/okd-95m5h-api-internal
    forwardingRuleIp: 10.0.0.2
    healthState: HEALTHY
    instance: https://www.googleapis.com/compute/v1/projects/yb-openshift-dev/zones/us-east1-b/instances/okd-95m5h-bootstrap
    ipAddress: 10.0.0.6
    port: 80
  kind: compute#backendServiceGroupHealth
---
backend: https://www.googleapis.com/compute/v1/projects/yb-openshift-dev/zones/us-east1-c/instanceGroups/okd-95m5h-master-us-east1-c
status:
  healthStatus:
  - forwardingRule: https://www.googleapis.com/compute/v1/projects/yb-openshift-dev/regions/us-east1/forwardingRules/okd-95m5h-api-internal
    forwardingRuleIp: 10.0.0.2
    healthState: UNHEALTHY
    instance: https://www.googleapis.com/compute/v1/projects/yb-openshift-dev/zones/us-east1-c/instances/okd-95m5h-master-1
    ipAddress: 10.0.0.3
    port: 80
  kind: compute#backendServiceGroupHealth
---
backend: https://www.googleapis.com/compute/v1/projects/yb-openshift-dev/zones/us-east1-d/instanceGroups/okd-95m5h-master-us-east1-d
status:
  healthStatus:
  - forwardingRule: https://www.googleapis.com/compute/v1/projects/yb-openshift-dev/regions/us-east1/forwardingRules/okd-95m5h-api-internal
    forwardingRuleIp: 10.0.0.2
    healthState: UNHEALTHY
    instance: https://www.googleapis.com/compute/v1/projects/yb-openshift-dev/zones/us-east1-d/instances/okd-95m5h-master-2
    ipAddress: 10.0.0.4
    port: 80
  kind: compute#backendServiceGroupHealth
````
**Version**

Both the below versions are reproducable
`4.15.0-0.okd-2024-02-23-163410`
`4.17.0-okd-scos.0`

**How reproducible**

100% reproducible with the steps described [here](https://docs.okd.io/latest/installing/installing_gcp/installing-gcp-default.html) 

**Log bundle**

[log-bundle-20250425151128.tar.gz](https://github.com/user-attachments/files/19911684/log-bundle-20250425151128.tar.gz)
