### ISSUE TITLE
Resources of ExternalIP are used by allowedCIDRs and autoAssignCIDRs and lead to duplicate IP conflicts

### ISSUE THREAD

**Issue by khessert** [okd-project/okd#2206]
### Describe the bug

IPs in use by manually specifying ExternalIP from the autoAssignCIDRs range might get auto assigned to a different service

Example config
```
oc edit Network.config.openshift.io cluster
```
```
spec:
  clusterNetwork:
  - cidr: 172.22.0.0/17
    hostPrefix: 24
  externalIP:
    autoAssignCIDRs:
    - 10.104.129.32/27
    policy:
      allowedCIDRs:
      - 10.104.129.32/27
  networkType: OpenShiftSDN
```

From the documentation

> OpenShift Container Platform supports both the automatic and manual assignment of IP addresses, where each address is guaranteed to be assigned to a maximum of one service. This configuration ensures that each service can expose its chosen ports regardless of the ports exposed by other services.

https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html/networking/configuring-ingress-cluster-traffic#configuration-externalip_configuring-externalip

There seems to be a bug or unclear wording.

Steps to reproduce
- Create a service of type ClusterIP and specify an ExternalIP of the autoAssignCIDRs range
- Create services of type LoadBalancer until one of those gets assigned the IP from the step above

### Version

4.16.0-okd-scos.1 IPI

### Reproducibility

100%
