### ISSUE TITLE
Init:ImagePullBackOff for multus-additional-cni-plugins pods in disconnected environments

### ISSUE THREAD

**Issue by raballew** [okd-project/okd#925]
**Describe the bug**

In a disconnected environment, when mirroring the `4.8.0-0.okd-2021-10-10-030117` release to a local registry some of the images do not preserve their digests. Might be related to https://github.com/openshift/okd/issues/402.

```bash
oc adm -a ~/pull-secret.txt release mirror \
  --from=quay.io/openshift/okd:$OKD_VERSION \
  --to=$HOSTNAME:5000/openshift/okd \
  --to-release-image=$HOSTNAME:5000/openshift/okd:$OKD_VERSION
```

Hence some pods are stuck in `Init:ImagePullBackOff`.

```bash
[okd@services installer]$ oc get pods -n openshift-multus
NAME                                  READY   STATUS                  RESTARTS   AGE
multus-8cnn6                          1/1     Running                 0          9m56s
multus-9ff8h                          1/1     Running                 0          9m49s
multus-additional-cni-plugins-2f5s2   0/1     Init:ImagePullBackOff   0          9m58s
multus-additional-cni-plugins-2k2w2   0/1     Init:ImagePullBackOff   0          9m48s
multus-additional-cni-plugins-6rtpz   0/1     Init:ImagePullBackOff   0          9m49s
multus-additional-cni-plugins-8nmm8   0/1     Init:ImagePullBackOff   0          9m57s
multus-additional-cni-plugins-8r4w6   0/1     Init:ImagePullBackOff   0          9m56s
multus-additional-cni-plugins-94t94   0/1     Init:ImagePullBackOff   0          9m57s
multus-additional-cni-plugins-gbmhz   0/1     Init:ImagePullBackOff   0          9m57s
multus-additional-cni-plugins-jz6t4   0/1     Init:ImagePullBackOff   0          9m53s
multus-additional-cni-plugins-mt66t   0/1     Init:ImagePullBackOff   0          9m56s
multus-additional-cni-plugins-nsskf   0/1     Init:ImagePullBackOff   0          9m56s
multus-additional-cni-plugins-rc99z   0/1     Init:ImagePullBackOff   0          9m51s
multus-additional-cni-plugins-x8tqh   0/1     Init:ImagePullBackOff   0          9m53s
multus-admission-controller-fzwl5     2/2     Running                 0          9m27s
multus-admission-controller-p2292     2/2     Running                 0          9m26s
multus-admission-controller-wnghb     2/2     Running                 0          9m27s
multus-bqqcm                          1/1     Running                 0          9m53s
multus-d578s                          1/1     Running                 0          9m52s
multus-dx4gn                          1/1     Running                 0          9m58s
multus-dztgr                          1/1     Running                 0          10m
multus-j4692                          1/1     Running                 0          9m57s
multus-m59j4                          1/1     Running                 0          9m50s
multus-tczcs                          1/1     Running                 0          9m58s
multus-tzhcd                          1/1     Running                 0          9m49s
multus-v4trn                          1/1     Running                 0          9m57s
multus-z6q2h                          1/1     Running                 0          9m56s
network-metrics-daemon-24dcg          2/2     Running                 0          9m49s
network-metrics-daemon-4n9bx          2/2     Running                 0          9m57s
network-metrics-daemon-5qfsk          2/2     Running                 0          9m50s
network-metrics-daemon-87x4x          2/2     Running                 0          9m49s
network-metrics-daemon-9ttmr          2/2     Running                 0          9m52s
network-metrics-daemon-gxnrs          2/2     Running                 0          9m58s
network-metrics-daemon-n8dqx          2/2     Running                 0          9m56s
network-metrics-daemon-qdpfd          2/2     Running                 0          9m48s
network-metrics-daemon-qwk4t          2/2     Running                 0          9m56s
network-metrics-daemon-qx72r          2/2     Running                 0          9m57s
network-metrics-daemon-t84k6          2/2     Running                 0          9m54s
network-metrics-daemon-x2ktc          2/2     Running                 0          9m49s
```

Whereas the status of the errornous pods shows the following:

```yaml
  - image: quay.io/openshift/okd-content@sha256:23fec69e66db7ccfb13e4fd2d53e8f5d525a4828bdb31f155a04476745524ad9
    imageID: ""
    lastState: {}
    name: routeoverride-cni
    ready: false
    restartCount: 0
    state:
      waiting:
        message: Back-off pulling image "quay.io/openshift/okd-content@sha256:23fec69e66db7ccfb13e4fd2d53e8f5d525a4828bdb31f155a04476745524ad9"
        reason: ImagePullBackOff
```

And the image content source policies are specified as follows in the `install-config.yaml`:

```yaml
[...]
imageContentSources:
- mirrors:
  - $HOSTNAME:5000/openshift/okd
  source: quay.io/openshift/okd
- mirrors:
  - $HOSTNAME:5000/openshift/okd
  source: quay.io/openshift/okd-content
```

Even if manually copying the image to the local registry with Skopeo the pods are stuck. Doing a inspect of `$HOSTNAME:5000/openshift/okd@sha256:23fec69e66db7ccfb13e4fd2d53e8f5d525a4828bdb31f155a04476745524ad9` fails too with the following error message:

```
skopeo copy -a --authfile ~/pull-secret.txt docker://quay.io/openshift/okd-content@sha256:23fec69e66db7ccfb13e4fd2d53e8f5d525a4828bdb31f155a04476745524ad9 docker://$HOSTNAME:5000/openshift/okd
skopeo inspect --authfile ~/pull-secret.txt docker://$HOSTNAME:5000/openshift/okd@sha256:23fec69e66db7ccfb13e4fd2d53e8f5d525a4828bdb31f155a04476745524ad9
FATA[0000] Error parsing image name "docker://$HOSTNAME:5000/openshift/okd@sha256:23fec69e66db7ccfb13e4fd2d53e8f5d525a4828bdb31f155a04476745524ad9": reading manifest sha256:23fec69e66db7ccfb13e4fd2d53e8f5d525a4828bdb31f155a04476745524ad9 in $HOSTNAME:5000/openshift/okd: manifest unknown: manifest unknown 
```

**Version**
Disconnected, UPI, 4.8.0-0.okd-2021-10-10-030117

**How reproducible**
100%
