### ISSUE TITLE
BuildConfig status missing `imageChangeTriggers:`

### ISSUE THREAD

**Issue by bdurrow** [okd-project/okd#929]
**Describe the bug**

Since upgrading from `4.7.0-0.okd-2021-09-19-013247` to `4.8.0-0.okd-2021-10-10-030117` I see lots of `BuildConfigTriggerFailed `  Warning event every 15 minutes that look like this, one each for almost all of my buildConfigs:
```
pim-build                                          4m33s       Warning   BuildConfigTriggerFailed                     buildconfig/s2i-wildfly-hbee                                                 error triggering Build for BuildConfig pim-build/s2i-wildfly-hbee: Internal error occurred: build config pim-build/s2i-wildfly-hbee has already instantiated a build for imageid image-registry.openshift-image-registry.svc:5000/openshift/wildfly@sha256:4e2dc4d7b87b1d26ca7b302ed10da6875602a2a618a28814ccd8e96ccfab6f4d
```

When I look at the BuildConfig object I see that the status is just:
```
status:
  lastVersion: 7
```

If I trigger a new build I the status is updated with `imageChangeTriggers` and the `BuildConfigTriggerFailed ` event is no longer emitted  for that buildConfig:
```
status:
  imageChangeTriggers:
  - from:
      name: wildfly:14.0
      namespace: openshift
    lastTriggerTime: null
    lastTriggeredImageID: image-registry.openshift-image-registry.svc:5000/openshift/wildfly@sha256:4e2dc4d7b87b1d26ca7b302ed10da6875602a2a618a28814ccd8e96ccfab6f4d
  lastVersion: 8
```

**Version**

OKD GCP IPI 4.8.0-0.okd-2021-10-10-030117

**How reproducible**

Unknown

**Log bundle**

Unless you think there is something specifically helpful you would find in the must-gather archive I am not going to publish one.  It takes a lot of time to audit the information in one and strip out sensitive information.

**Comment by vrutkovs** [comment]
This imagestreamtag is defined as:
```
    - name: '14.0'
      annotations:
        description: >-
          Build and run WildFly 14 applications on CentOS 7. For more
          information about using this builder image, including OpenShift
          considerations, see
          https://github.com/openshift-s2i/s2i-wildfly/blob/master/README.md.
        iconClass: icon-wildfly
        openshift.io/display-name: WildFly 14
        openshift.io/provider-display-name: 'Red Hat, Inc.'
        sampleRepo: 'https://github.com/openshift/openshift-jee-sample.git'
        supports: 'wildfly:14,jee,java'
        tags: 'builder,wildfly,java'
        version: '14.0'
      from:
        kind: DockerImage
        name: 'docker.io/openshift/wildfly-140-centos7:latest'
      generation: 8
      importPolicy: {}
      referencePolicy:
        type: Local
```
Any import error for wildfly imagestream in `openshift` namespace?
